### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by arijit4** [patrykandpatrick/vico#166]
Why not add a `.apk` file to every release so that we understand how every chart ends up looking?

**Comment by patrickmichalik** [comment]
Sounds good. We’ll look into it. Thanks for the suggestion!

**Comment by patrickmichalik** [comment]
Hello! From now on, each release will include the corresponding version of the sample app as an attachment—see [the latest release](https://github.com/patrykandpatrick/vico/releases/tag/v1.6.4) for an example. Cheers!
