### ISSUE TITLE
Allow scrollable (Bar)Chart to be syncronized with a external scrollbar

### ISSUE THREAD

**Issue by Syrou** [patrykandpatrick/vico#168]
Hi, once again thanks for pretty much making the best graph library. In our product we have a need for being able to fast go to the beginning, the middle and the end of the (bar)chart because we have lots of data.

Would it be possible to open up so the scroll position of the bar chart can be controlled from outside the (bar)chart as well being synchronized so that whenever someone scrolls in the (bar)chart, the position is broadcasted out as well. This means we would need to have three properties being made available as a lambda:

min, max and currentPosition

This would open up for a "scroll overview" of sorts, which makes navigating large graphs very easy for the user

**Comment by patrickmichalik** [comment]
Hello, and thanks for the kind words! Sure, we’ll add such functionality. We were planning on implementing it somewhere down the line, but now that it’s been requested, I’ll prioritize this.

**Comment by patrickmichalik** [comment]
[Vico 1.6.2](https://github.com/patrykandpatrick/vico/releases/tag/v1.6.2) introduces the feature in question. In the `compose` module, `Chart` now has a `chartScrollState` parameter, and in the `views` module, `BaseChartView` has functions such as `registerScrollListener` and `scrollBy`. Please feel free to let us know if you have any questions, and thank you for the suggestion!
