### ISSUE TITLE
Marker memory

### ISSUE THREAD

**Issue by crescom-twkim** [patrykandpatrick/vico#181]
Hello, thank you for your wonderful library.
However, there is a problem during use. When I use markers and labels, memory usage increases every time I touch it.  Where do you store the values of markers and labels? Is there a solution?

**Comment by Gowsky** [comment]
Hi @crescom-twkim I can't see such a problem in our sample app. Can you provide a MRE?

**Comment by crescom-twkim** [comment]
I found a problem somewhere else. Thank you.
