### ISSUE TITLE
Large number of entries, how to scale the x-Axis

### ISSUE THREAD

**Issue by johnnycube** [patrykandpatrick/vico#182]
Hi,

thanks for you library. Like it a lot.

However, I have a problem that I cannot solve regarding the visualization of large amount of data.

I want to show a line graph with approx. 1000 entries. This works perfectly, however, the line chart is scrolling and not showing all entries. What is the correct way to scale the x-Axis to show all entries and disable the scrolling to left and right?

**Comment by patrickmichalik** [comment]
Hello! We’re glad Vico has been useful to you. Could you let us know if you’re using Vico with Jetpack Compose or the view system? The steps to achieve the desired effect differ between the two modules.

**Comment by johnnycube** [comment]
Hi, thanks for the quick reply. I'm using the compose system with M3 styling (if that matters)

**Comment by patrickmichalik** [comment]
Thanks for the update. To disable scrolling, use the `chartScrollSpec` parameter of `Chart`, passing `rememberChartScrollSpec(isScrollEnabled = false)`. The chart will be scaled down. Should you wish to decrease the number of ticks along the horizontal axis (or axes), use the `tickPosition` parameter of `topAxis` and `bottomAxis`, passing something along the lines of `HorizontalAxis.TickPosition.Edge(spacing = 100)`.

**Comment by johnnycube** [comment]
Perfect! isScrollEnabled did the job. Will have to play with spacing a bit in order to get in working - but it looks nice already!

So just one final question - dont want to make this my personal helpdesk - There is a padding before and after the line in my linechart (when i reduce the number of element to 5-10). How do I get rid of it and let the zero of the axis start at the y-Axis and let the graph end at the "end of the chart".

![image](https://user-images.githubusercontent.com/1459652/216142765-0f038dde-c058-4227-a590-7bdebbe14394.png)

**Comment by patrickmichalik** [comment]
Using the `pointPosition` parameter of `lineChart`, you should be able to close the gap at the start of the chart. This is demonstrated in the third sample chart (see [here](https://github.com/patrykandpatrick/vico/blob/master/sample/src/main/java/com/patrykandpatrick/vico/sample/chart/Chart3.kt#L49)). I believe, however, that this will leave an empty segment at the end of the chart, since the number of segments won’t be decreased. This is something that we plan on looking into. I’ll prioritize it.

**Comment by johnnycube** [comment]
Thanks for pointing it out - no need to prioritize just for me!

This can be closed. All questions have been answered

**Comment by BartNijland91** [comment]
@patrickmichalik Do you have an idea what I could do to add extra padding to end of a scrollable chart?

**Comment by patrickmichalik** [comment]
Could you expand on that, @BartNijland91? Where exactly would you like to see more horizontal space?
