### ISSUE TITLE
Marker text color

### ISSUE THREAD

**Issue by tabula-rasa** [patrykandpatrick/vico#183]
Hello.
I'm having a hard time changing marker's label text color in a view system. Marker code:
```
fun createMarker() : Marker {

    val labelBackgroundShape = MarkerCorneredShape(all = Corner.FullyRounded)

    val label = textComponent {
        color = Color.BLACK
        padding = dimensionsOf(horizontalDp = 18f, verticalDp = 14f)
        typeface = Typeface.MONOSPACE
        background = ShapeComponent(shape = labelBackgroundShape, color = Color.BLACK)
            .setShadow(
                color = Color.BLACK.copyColor(alpha = 0.5f),
                radius = LABEL_BACKGROUND_SHADOW_RADIUS,
                dy = LABEL_BACKGROUND_SHADOW_DY,
                applyElevationOverlay = true,
            )
    }

    val indicator = OverlayingComponent(
        outer = ShapeComponent(shape = pillShape, color = Color.BLACK.copyColor(alpha = 0.25f)),
        innerPaddingAllDp = 10f,
        inner = OverlayingComponent(
            outer = ShapeComponent(shape = pillShape),
            inner = ShapeComponent(shape = pillShape, color = Color.GRAY),
            innerPaddingAllDp = 5f,
        ),
    )

    val guideline = LineComponent(
        color = Color.LTGRAY,
        thicknessDp = 2f,
        shape = DashedShape(shape = pillShape, dashLengthDp = 8f, gapLengthDp = 4f),
    )

    return object : MarkerComponent(
        label = label,
        indicator = indicator,
        guideline = guideline,
    ) {
        init {
            indicatorSizeDp = INDICATOR_SIZE_DP
        }

        override fun getInsets(
            context: MeasureContext,
            outInsets: Insets,
            segmentProperties: SegmentProperties
        ) {
            return with(context) {
                outInsets.top = label.getHeight(this) + labelBackgroundShape.tickSizeDp.pixels +
                        SHADOW_RADIUS.pixels * SHADOW_RADIUS_MULTIPLIER - SHADOW_DY.pixels
            }
        }
    }
}

private const val LABEL_BACKGROUND_SHADOW_RADIUS = 4f
private const val LABEL_BACKGROUND_SHADOW_DY = 2f
private const val INDICATOR_SIZE_DP = 36f
private const val SHADOW_RADIUS_MULTIPLIER = 1.3f
private const val SHADOW_DY = 2f
private const val SHADOW_RADIUS = 4f
```
No matter how I change ```val label = textComponent {.. color = Color.BLACK .. }``` it always remains gray. What am I doing wrong?)
Thank you.

**Comment by patrickmichalik** [comment]
Hello! The color you’re seeing corresponds to the color of the line or column being highlighted. `DefaultMarkerLabelFormatter` is responsible for this—see [here](https://github.com/patrykandpatrick/vico/blob/master/vico/core/src/main/java/com/patrykandpatrick/vico/core/marker/DefaultMarkerLabelFormatter.kt#L45). To achieve the desired result, you can create a `MarkerLabelFormatter` implementation that doesn’t alter the text color, using the `labelFormatter` field of `MarkerComponent` to apply the `MarkerLabelFormatter`. The `TextComponent`’s intrinsic color will then be used.

**Comment by slimaneouragh** [comment]
Hi bro thanks for this great Library but i have i question how i can change the initialScroll for chart because the enum class initialScroll it has two constant Start and End but i wanna customize it like on 10f or 5f

**Comment by patrickmichalik** [comment]
Unfortunately, @slimaneouragh, there’s no such feature at the moment. You could try programmatically updating the scroll value to the desired one right after the chart is created, but the result may not be perfect. If you’d like to request this feature, or if you have any further questions, please open a dedicated issue. Cheers!

**Comment by tabula-rasa** [comment]
Thank you, @patrickmichalik! That did the trick!

**Comment by patrickmichalik** [comment]
You’re welcome! We’ll discuss adding to the `DefaultMarkerLabelFormatter` constructor a parameter that would let you disable this behavior without having to create a `MarkerLabelFormatter` implementation.

**Comment by patrickmichalik** [comment]
[Vico 1.12.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.12.0) turns `DefaultMarkerLabelFormatter` into a regular class and gives it a `colorCode` property, so instead of creating a custom `MarkerLabelFormatter` implementation, you can now use `DefaultMarkerLabelFormatter(colorCode = false)`.

**Comment by anchithAcharya** [comment]
> [Vico 1.12.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.12.0) turns `DefaultMarkerLabelFormatter` into a regular class and gives it a `colorCode` property, so instead of creating a custom `MarkerLabelFormatter` implementation, you can now use `DefaultMarkerLabelFormatter(colorCode = false)`.

Hi @patrickmichalik, how do I do this in Vico 2.0.0-alpha.24? I cannot find `colorCode`, and I'm having trouble changing the color of the marker label text.

**Comment by patrickmichalik** [comment]
@anchithAcharya, `DefaultMarkerLabelFormatter` is now called `DefaultCartesianMarkerValueFormatter`. There’s a `colorCode` constructor parameter. Please see [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/markers/) for more.
