### ISSUE TITLE
Setting colors question

### ISSUE THREAD

**Issue by tabula-rasa** [patrykandpatrick/vico#186]
Hi, Patrick.
Can you please give a little tip, how to set line-chart colors? I have a dark app theme, so I need to adjust colors for axes, labels and line chart itself. 
Thank you.

**Comment by patrickmichalik** [comment]
Hello! Just to confirm, is this referring to the view system, similarly to your previous issue?

**Comment by tabula-rasa** [comment]
Sure, forgot to mention that. View system.

**Comment by patrickmichalik** [comment]
I’d suggest taking a look at the third sample chart. [Here](https://github.com/patrykandpatrick/vico/blob/master/sample/src/main/res/layout/chart_3.xml) is the XML layout file, and [here](https://github.com/patrykandpatrick/vico/blob/master/sample/src/main/res/values/chart_3_styles.xml) is the file where the styles are housed. The `lineChartStyle` attribute of `ChartView` allows for customizing the line chart itself, and you can use the four `*axisStyle` attributes to customize the chart axes. Please see [this wiki page](https://patrykandpatrick.com/vico/wiki/customization/customization-in-the-view-system/#basechartview-attributes) for a rundown of all the available XML attributes. If you face any issues, feel free to let me know.

**Comment by tabula-rasa** [comment]
Thank you, will take a look )

**Comment by tabula-rasa** [comment]
That was exactly, what I need. Thank you.

**Comment by patrickmichalik** [comment]
You’re welcome!
