### ISSUE TITLE
Can marker be customized as composable?

### ISSUE THREAD

**Issue by dylan-kwon** [patrykandpatrick/vico#189]
Can marker be customized as composable?

Currently, it seems that only data values are configured. I want to show more data when data is clicked.

**Comment by patrickmichalik** [comment]
Hello! A chart marker must be an implementation of the `Marker` interface, so it can’t be a composable function. However, you can still draw more or less anything, as a `DrawContext` instance is exposed. Classes like `TextComponent` and `ShapeComponent` are available for you to use.
