### ISSUE TITLE
[Feature request] LineChart custom labels

### ISSUE THREAD

**Issue by raudonikis** [patrykandpatrick/vico#190]
(Jetpack Compose, LineChart) The spacing provided by the library does not suit my specific use case, for example I need these labels: [1,5,10,15,20,25,31] when the entry count is 31 (for the month of January). It would be great to have more customisation options, maybe providing a list of entries that should show a label? I'm adding an example of what it would look like:

![image](https://user-images.githubusercontent.com/46673448/218952343-c9f71515-ccd1-4820-89a6-1b072faa7db5.png)

**Comment by patrickmichalik** [comment]
Hello! This functionality has been introduced with [Vico 1.7.2](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.2). Thanks for the suggestion!
