### ISSUE TITLE
How to add a step in Y axis ?

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#194]

**Comment by patrickmichalik** [comment]
Hello! For vertical axes, you can specify the label count, which ultimately determines the step.

**Comment by abderhim** [comment]
Thank you !

**Comment by patrickmichalik** [comment]
Sure thing!

**Comment by mikfas** [comment]
Where should I specify the label count? I can only see maxlabelcount inside startaxis. Thanks

**Comment by patrickmichalik** [comment]
So long as the value of `maxLabelCount` isn’t higher than the number of labels that there is room for, the value of `maxLabelCount` is the number of labels displayed.

**Comment by mikfas** [comment]
Thanks a lot

**Comment by patrickmichalik** [comment]
You’re welcome!
