### ISSUE TITLE
Is it possible to write the Y labels inside the container and under the horizontal lines ?

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#195]

**Comment by patrickmichalik** [comment]
Hello! Yes, this is possible. Please see [`VerticalAxis.HorizontalLabelPosition.Inside`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.axis.vertical/-vertical-axis/-horizontal-label-position/-inside) and [`HorizontalAxis.VerticalLabelPosition.Bottom`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.axis.vertical/-vertical-axis/-vertical-label-position/-bottom).

**Comment by abderhim** [comment]
Thank you.

**Comment by patrickmichalik** [comment]
You’re welcome!
