### ISSUE TITLE
Line graph: Multiple data points at same X

### ISSUE THREAD

**Issue by TomBell-Trove** [patrykandpatrick/vico#197]
My graph's X axis corresponds to a date and shows deposit events.  For accuracy the back end sends this data such that multiple events can happen on one day, to indicate that a deposit happened on that day.  For example there could be two entries for 1/3/2023, one with $1000 when the day stated, and one with $1500 following a deposit event later that day.  

![image](https://user-images.githubusercontent.com/88296617/223288619-b78c32a2-0218-43d0-a06b-ab718776d69a.png)

Vico seems to be placing subsequent entries further along the X axis, even if I have the same X value in each entry.  Note the slanted increases rather than them being vertical.  Is there a way to achieve this?  This behaviour is a biz and design requirement so I can't deviate from it - but I'd like to move on from MPAndroidCharts!

![image](https://user-images.githubusercontent.com/88296617/223289023-56d52007-93a4-4bab-b13e-402751687bc3.png)

**Comment by Gowsky** [comment]
Hello @TomBell-Trove, 
Can you confirm that you're using a [DefaultPointConnector](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart/-default-point-connector/) with `cubicStrength` equal to `0`, and that x-axis `Float` values are exactly the same?

**Comment by patrickmichalik** [comment]
Hello! As such, it’s impossible for a line chart to have two points with the same _x_ coordinate in a single data set, but I believe you can achieve the desired effect by creating a custom `LineChart.LineSpec.PointConnector`. You’d need to use `lineTo` twice, once for the horizontal line segment, and once for the vertical one.

**Comment by patrickmichalik** [comment]
Hello! Initializing `DefaultPointConnector` with `cubicStrength` equal to zero and giving the points that are to be displayed on top of one another identical _x_ values, as @Gowsky has mentioned, produces the following result.

<img src="https://user-images.githubusercontent.com/120058021/223375426-3fea1a9b-4724-40f0-a09a-f1665e119768.png" width="360" />

With that said, my suggestion for creating stepped line charts is to write a custom `LineChart.LineSpec.PointConnector` implementation that connects points by drawing two line segments: a horizontal one and a vertical one. This way, the `ChartEntryModel` doesn’t have to be adapted.

**Comment by TomBell-Trove** [comment]
Thank you both.  I was using a simple path.lineTo() connector and will investigate further <3

**Comment by patrickmichalik** [comment]
You’re welcome!
