### ISSUE TITLE
Is it possible to show markers only for the data that is touched?

### ISSUE THREAD

**Issue by dylan-kwon** [patrykandpatrick/vico#199]
I want the marker to display only one data the user has touched.

But now 'VICO' seems to show both data on the same x-axis.

In the screenshot below, if the user touches the data of `data set 1`, I want to display only the data of `data set 1` as a marker.

<img width="386" alt="스크린샷 2023-03-08 오전 11 03 58" src="https://user-images.githubusercontent.com/21299684/223601098-c4d6e9e4-6d66-4e8b-ad3e-a7efe2880b1a.png">

**Comment by patrickmichalik** [comment]
Hello! I’d like to preface by noting that the yellow boxes in the screenshot are axis labels, not markers. In Vico, a marker highlights all entries in a given chart segment, and I’m afraid this cannot be changed. The reason for this is, among other things, that if each entry had its own touch target, and two entries happened to be right next to each other vertically, it would be hard for the user to hit the right touch target.

**Comment by dylan-kwon** [comment]
Can you optionally add a this feature?

**Comment by patrickmichalik** [comment]
We’ve discussed this, and unfortunately, due to the aforementioned UX concerns, we don’t plan on adding such a feature.
