### ISSUE TITLE
How to set number of labels in Xaxis?  there is no param like maxLabelCount in Yaxis

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#201]

**Comment by patrickmichalik** [comment]
Hello! The number of labels along a horizontal axis depends on two things: the number of chart entries and the label spacing. [`HorizontalAxis.TickPosition.Center`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.axis.horizontal/-horizontal-axis/-tick-position/-center) allows for customizing the latter.

**Comment by abderhim** [comment]
Thank you for your response,
but how can i draw guidlines only for the visible Labels? for example i want two labels with two guidlines only.

**Comment by patrickmichalik** [comment]
That’s the default behavior—a guideline is drawn for every label. If there are only two labels, there will be exactly two guidelines.

**Comment by abderhim** [comment]
Thanks a lot!

**Comment by patrickmichalik** [comment]
You’re welcome!
