### ISSUE TITLE
How can i make columns of chart colored with different colors ?

### ISSUE THREAD

**Issue by mhrohani1385** [patrykandpatrick/vico#206]
```kotlin
Chart(
    chart =
        columnChart(
            columns = listOf(LineComponent(Color.Black.toArgb()), LineComponent(Color.Red.toArgb()))
        ),
    model = entryModelOf(0 to 1, 1 to 5),
    startAxis = startAxis(),
    bottomAxis = bottomAxis()
)
```

But result's like this :    
While I expect one to be black and one to be red !    
    
![Screenshot_1678563891](https://user-images.githubusercontent.com/65995652/224508720-86df2b80-5885-41b3-b552-5c4a4b6f04db.png)

**Comment by mhrohani1385** [comment]
I think if I can use a something like this , so much greater :

```kotlin
Chart(
    chart =
        columnChart(
            columns = 
                            { value, index ->
                                 LineComponent(
                                      Color(value.coerceIn(0f, 1f), 0.4f, 0.5f).toArgb()
                                  )
                            }
        ),
    model = entryModelOf(0 to 1, 1 to 5),
    startAxis = startAxis(),
    bottomAxis = bottomAxis()
)
```

**Comment by mhrohani1385** [comment]
Of course, I also noticed that sometimes data labels didn't display.

**Comment by mhrohani1385** [comment]
Hello, i am waiting for a solution for this !

**Comment by Gowsky** [comment]
Hello!
Only separate data sets can have different column colors in a single the `ColumnChart`.
In your example it would be like to following:
```kotlin
val model = entryModelOf(entriesOf(0 to 1), entriesOf(1 to 5))
```
or
```kotlin
chartEntryModelProducer.setEntries(entriesOf(0 to 1), entriesOf(1 to 5))
```
Then you can set two different column styles like in the [sample app](https://github.com/patrykandpatrick/vico/blob/e5d80aef9e4e62157d4fe867832545fae2807d95/sample/src/main/java/com/patrykandpatrick/vico/sample/chart/Chart6.kt#L54).

If you don’t want to use different data sets, you’d have to use a [DynamicShader](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.component.shape.shader/-dynamic-shader/?query=fun%20interface%20DynamicShader) which can be set to the `LineComponent`.

**Comment by mhrohani1385** [comment]
Thanks a lot !
Please don't close the issue, I will try to implement this and let you know if my problem solved or not.

**Comment by mhrohani1385** [comment]
Hello . When the columns are grouped, they colored successfully. but unfortunately, the distance between them increases and the data labels are not displayed completely. I need to see the data label in full text and this is necessary, while there is no place for them and **( ... )** arises .
It would be great if this problem is solved too ! 🙏🤩

**Comment by Gowsky** [comment]
Using [`MergeMode.Stack`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart.column/-column-chart/-merge-mode/?query=enum%20MergeMode%20:%20Enum%3CColumnChart.MergeMode%3E#-1541829969%2FClasslikes%2F186187275) when constructing the `ColumnChart` should fix your problem.

**Comment by mhrohani1385** [comment]
> Using [`MergeMode.Stack`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart.column/-column-chart/-merge-mode/?query=enum%20MergeMode%20:%20Enum%3CColumnChart.MergeMode%3E#-1541829969%2FClasslikes%2F186187275) when constructing the `ColumnChart` should fix your problem.

Hi again !
I tried stack merge mode but in it some data libels doesn't show.

**Comment by mhrohani1385** [comment]
> Hi again ! I tried stack merge mode but in it some data libels doesn't show. [ It doesn't have (...), some labels shows and some not ]

I understood always only last column has data label !!

**Comment by mhrohani1385** [comment]
how to use a data label value formatter with *value* of *xAxis* ?

**Comment by mhrohani1385** [comment]
I need a data label based on xAxis or An axis label in the bottom of the columns and not in the bottom of tick

**Comment by mhrohani1385** [comment]
My problem is solved . 
Thanks a lot !

**Comment by mhrohani1385** [comment]
My problem is solved .
Thanks a lot !
