### ISSUE TITLE
How to get rid of the extra padding at top and bottom?

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#207]
<img width="327" alt="Screenshot 2023-03-13 at 11 11 42" src="https://user-images.githubusercontent.com/26873347/224672293-0b6ade6d-f29f-4093-83be-accdc25b614e.png">

**Comment by patrickmichalik** [comment]
Hello! This padding isn’t part of the chart. The chart is placed and centered in a `Box` with a static height, padding, and a rounded background.

**Comment by abderhim** [comment]
so can we customize the modifier of that box so i can get rid of that padding?

**Comment by patrickmichalik** [comment]
The `Box` is added by the sample app. It isn’t part of the `Chart` composable, which has no margins or padding by default.

**Comment by abderhim** [comment]
but even when i don't put the Chart in a box i will still have the same issue.

**Comment by patrickmichalik** [comment]
That shouldn’t happen. If your chart has a marker, space will be made at the top for the marker to fit, but the `Chart` composable has no margins or padding by default, and the entire area of the composable is used for drawing. If you’re seeing unwanted empty space, please share your code, and we’ll take a look.

**Comment by patrickmichalik** [comment]
If you’d like to move the marker into the chart area, thus eliminating the need for the empty space, you can create a custom [`Marker`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.marker/-marker) implementation. [`MarkerComponent`](https://github.com/patrykandpatrick/vico/blob/master/vico/core/src/main/java/com/patrykandpatrick/vico/core/component/marker/MarkerComponent.kt) should be a good starting point. Insets are applied via [`ChartInsetter#getInsets`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart.insets/-chart-insetter/get-insets).
