### ISSUE TITLE
Hello, how do you customise the Y-axis data?

### ISSUE THREAD

**Issue by gracewang9** [patrykandpatrick/vico#208]
Hello, how do you customise the x-axis data?

**Comment by patrickmichalik** [comment]
Hello! This is described [here](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values).

**Comment by gracewang9** [comment]
Thanks, I've seen this column; but I don't know how to display the same value of "0.5kw" for the X-axis data; I want to display: listOf ("0.5kw", "1.0kw", "1.5kw", "2.0kw")

**Comment by gracewang9** [comment]
This is the effect I wanted：
![1678758215636](https://user-images.githubusercontent.com/8500399/224870565-2a80e62a-026c-437e-bb3b-fee7adba2599.jpg)

This is the effect achieved：
![WechatIMG2](https://user-images.githubusercontent.com/8500399/224870668-850f0599-05b4-4b40-aae0-b04501d79104.jpeg)

**Comment by gracewang9** [comment]
Sorry, I was wrong. It's the Y-axis.

**Comment by patrickmichalik** [comment]
I’d suggest using `DecimalFormatAxisValueFormatter` for the _y_-axis, providing a custom pattern with “kW” at the end. The constructor of this class has a parameter for the format, and you can use the parameter’s default value as a starting point.

**Comment by gracewang9** [comment]
Thank you very much for your answer, I found this way, maybe not elegant enough, but enough to achieve my needs
 
 axisValuesOverrider = AxisValuesOverrider.fixed(
                minY = 0.5f,
                maxY = 2.0f
            )

private val yAxisValue = listOf("0.5kw", "1.0kw", "1.5kw", "2.0kw")
    val startAxisValueFormatter =
        AxisValueFormatter<AxisPosition.Vertical.Start> { value, chartValues ->
            (chartValues.chartEntryModel.entries.first()
                .getOrNull((value * 2 - 1).toInt()) as? StartEntry)?.x?.toString().orEmpty().let {
                yAxisValue[it.toFloat().toInt()]
            }
        }

**Comment by patrickmichalik** [comment]
I’m glad you’ve found a solution. Without context, it’s hard for me make sense of this approach, but I believe you could use `value` more directly. If each chart entry’s _y_ value represents a kilowatt count, a `DecimalFormatAxisValueFormatter` instance with a custom pattern (as described in my previous comment) should suffice.

```kt
private val startAxisValueFormatter = DecimalFormatAxisValueFormatter<AxisPosition.Vertical.Start>("#.## kW;−#.## kW")
```

**Comment by gracewang9** [comment]
> 高兴您解决。。没有没有，我我难种种方法方法种，但理解这种，但但我我我我我您您您可以可以可以更直接地地地使用使用使用如果。目的目的目的_目的_`value`目的目的我之前的评论中所描述的）应该足够了。__`DecimalFormatAxisValueFormatter`
> 
> ```kotlin
> private val startAxisValueFormatter = DecimalFormatAxisValueFormatter<AxisPosition.Vertical.Start>("#.## kW;−#.## kW")
> ```

Thank you very much, that's what I did

**Comment by gracewang9** [comment]
> I’m glad you’ve found a solution. Without context, it’s hard for me make sense of this approach, but I believe you could use `value` more directly. If each chart entry’s _y_ value represents a kilowatt count, a `DecimalFormatAxisValueFormatter` instance with a custom pattern (as described in my previous comment) should suffice.
> 
> ```kotlin
> private val startAxisValueFormatter = DecimalFormatAxisValueFormatter<AxisPosition.Vertical.Start>("#.## kW;−#.## kW")
> ```

Thank you very much, That's what I did

**Comment by patrickmichalik** [comment]
You’re welcome!
