### ISSUE TITLE
How to get grouped columns?

### ISSUE THREAD

**Issue by KesWalker** [patrykandpatrick/vico#209]
I have set the merge mode to be `Grouped` on my columns chart, as well as having multiple `FloatEntry`s with the same `x` axis. Yet the columns are not grouped?

**Comment by patrickmichalik** [comment]
Hello! For column grouping to work, you’ll need to have multiple data sets in your `ChartEntryModel`. A single data set shouldn’t contain multiple entries with the same _x_ value, but there can (and, in this case, should) be such overlaps between data sets. `ChartEntryModel#entries` is a list of lists, as is the `entryCollections` parameter of the `ChartEntryModelProducer` constructor. Each sublist is a data set.

**Comment by KesWalker** [comment]
Ahhh I see, thankyou Patrick! Helpful as always :)

**Comment by patrickmichalik** [comment]
You’re most welcome!
