### ISSUE TITLE
Marker is not updated if scrolling is enabled

### ISSUE THREAD

**Issue by Maliotis** [patrykandpatrick/vico#210]
**Describe the bug**
The Marker on the chart is not updating (following the users touch on the screen) while having default `chartScrollSpec` with scroll enabled. If you disabled it the `chartScrollSpec = rememberChartScrollSpec(isScrollEnabled = false)` the Marker updates ok. That seems to be only a compose issue 

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Run the sample app with the above settings

**Expected behavior**
The Marker should update like in the View tab

**Screenshots**

https://user-images.githubusercontent.com/30529446/224985249-93dba188-3877-40f2-bf0d-83cfa389194e.mp4

**Android versions**
Android 13

**Additional context**
version of lib 1.6.4

**Comment by patrickmichalik** [comment]
Thanks for the bug report! We’ll look into this.

**Comment by Gowsky** [comment]
Hello @Maliotis, unfortunately, due to the way Jetpack Compose scrolling API works internally we weren’t able to completely replicate the behavior present in the view system. Charts have to be scrolled first in order for the marker to respond to touch gestures upon swiping.
