### ISSUE TITLE
How to add my own Font style to the axis labels ? it only accepts TypeFace.

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#211]

**Comment by patrickmichalik** [comment]
Hello! The `Typeface` class doesn’t restrict you to any particular font family. See, for example, [`ResourcesCompat.getFont`](https://developer.android.com/reference/androidx/core/content/res/ResourcesCompat#getFont(android.content.Context,int)).

**Comment by abderhim** [comment]
Thank you.

**Comment by patrickmichalik** [comment]
You’re welcome!
