### ISSUE TITLE
A problem about gradle configuration

### ISSUE THREAD

**Issue by Eliaul** [patrykandpatrick/vico#215]
I have configured gradle according to the instructions, but Android Studio gives the following error message:
`D:/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.0/f7197e7cc76453ac59f8b0f8d5137cc600becd36/kotlin-stdlib-common-1.8.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
`

This is my module-level build.gradle:
```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.lbs'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.lbs"
        minSdk 28
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.1.1'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
    implementation 'androidx.activity:activity-compose:1.3.1'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.compose.material3:material3:1.0.0-alpha02'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"

    implementation "androidx.compose.material:material-icons-extended:$compose_version"
    implementation 'androidx.compose.material3:material3:1.1.0-alpha02'
    implementation "com.google.android.gms:play-services-location:17.0.0"

    implementation "androidx.navigation:navigation-compose:2.5.3"
    implementation "androidx.compose.material:material:1.3.1"

    implementation "com.patrykandpatrick.vico:compose-m3:1.6.3"
}
```

This is my project-level build.gradle:
```
buildscript {
    ext {
        compose_version = '1.1.1'
    }
    repositories {
        mavenCentral()
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false
}
```

**Comment by Gowsky** [comment]
Hello @Eliaul,
The error message is quite self-explanatory. You’re using 1.6.10 version of Kotlin, while Vico uses 1.8.0. Simply upgrade your Kotlin version.

**Comment by mhrohani1385** [comment]
with kotlin 1.8.0 i got :

e: This version (1.3.0) of the Compose Compiler requires Kotlin version 1.7.10 but you appear to be using Kotlin version 1.8.0 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

**Comment by patrickmichalik** [comment]
As per the error message, version 1.3.0 of the Compose compiler is incompatible with Kotlin 1.8.0, which you’ve updated to. Version 1.4.1 should work. Vico 1.6.5 will use Kotlin 1.8.10, and you’ll then be able to update the Compose compiler to version 1.4.3.

**Comment by mhrohani1385** [comment]
> As per the error message, version 1.3.0 of the Compose compiler is incompatible with Kotlin 1.8.0, which you’ve updated to. Version 1.4.1 should work. Vico 1.6.5 will use Kotlin 1.8.10, and you’ll then be able to update the Compose compiler to version 1.4.3.

kotlinCompilerExtensionVersion = "1.4.1"
solves problem

https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility

**Comment by mhrohani1385** [comment]
Thank you @patrickmichalik

**Comment by patrickmichalik** [comment]
You’re welcome!

**Comment by mhrohani1385** [comment]
I think this issue can be closed!
