### ISSUE TITLE
Problem with Persian value for xAxis 

### ISSUE THREAD

**Issue by mhrohani1385** [patrykandpatrick/vico#216]
![image](https://user-images.githubusercontent.com/65995652/226113791-ec77f1a9-2989-4c0a-9f88-99e8fc16f88e.png)

Hello ...
I need to use Persian text too in the center, like English text.
All English texts are placed in the center correctly but Persian texts make problems.

Also, thank you for your support. Do not be tired.

**Comment by mhrohani1385** [comment]
Hello again.
Please tag the issue as **enhancement**.
Thanks!

**Comment by mhrohani1385** [comment]
Is there no solution for now?

**Comment by Gowsky** [comment]
Hi @mhrohani1385, Unfortunately we don’t have any solution for now.

**Comment by patrickmichalik** [comment]
We’ve been able to reproduce the issue and will be looking into it. Thanks for the report!
