### ISSUE TITLE
Integer steps on Y axis

### ISSUE THREAD

**Issue by JanimeSenpai** [patrykandpatrick/vico#217]
I would like to make sure that steps on the y axis are either integer values, or steps of 0.5. I would like the graph to automatically set the step to an integer value, based on the numbers in the chartEntryModel.

This is what I would like to achieve: Steps of two on Y axis (Or steps of one, but the best would be if I could decide which.)
![image](https://user-images.githubusercontent.com/82962247/226214194-bc9970cf-1421-4d24-b30f-36046e95ba38.png)

This is what my code produces:
![image](https://user-images.githubusercontent.com/82962247/226214512-d4e259c4-0b8c-4031-82df-190a656cf20a.png)

Code:
`  val chartEntryModel = entryModelOf(entriesOf(7,5,6,2,11))
    Chart(
        chart = columnChart( ),
        model = chartEntryModel,
        startAxis = startAxis(),
        bottomAxis = bottomAxis(),
        )`

**Comment by mhrohani1385** [comment]
Hello
For start axis you can use maxLabelCount to last integer you need. 
And for value formatter use :
```kotlin
startAxis(
                                valueFormatter = remember {
                                    AxisValueFormatter { value, _ ->
                                        if(value.isFinite()) value.roundToInt().toString() else ""
                                    }
                                }
                                maxLabelCount = maxValue
                            )

**Comment by JanimeSenpai** [comment]
Thank you very much for your response. 
This solution works and is a very nice example of using the AxisValueFormatter.
![image](https://user-images.githubusercontent.com/82962247/226410369-b601ac0e-8fd8-4ad1-8942-e87bd87b9aaa.png)
Here is a screenshot, so if someone comes across this discussion can quickly see it.

**Comment by mhrohani1385** [comment]
I glad that my solution was helpful.
If your problem is solved, I think it is better to close the issue.
Thanks.

**Comment by JanimeSenpai** [comment]
I really thought that my issue was solved, but look at this screenshot:
I would like each "box" (or step, I do not know how should I precisely call it) to represent an integer value. here each box is 3/4 = 0.75. The first column's value is 2. 2/0.75=2.66 so the column is a little taller than two and half boxes. I would like to avoid having this.
![image](https://user-images.githubusercontent.com/82962247/226746404-60f778e0-9605-4be9-84d0-ae447cb5655c.png)

**Comment by patrickmichalik** [comment]
Hello! Thank you for your input, @mhrohani1385. You can update the label count for the start axis to achieve the desired result, @JanimeSenpai. Please see the `maxLabelCount` parameter of [`startAxis`](https://patrykandpatrick.com/vico/api/vico/compose/com.patrykandpatrick.vico.compose.axis.vertical/start-axis). In this case, a value of 4 should do the trick. The value can, of course, be calculated dynamically—it doesn’t have to be a hard-coded integer. That said, we’ll be looking into making improvements in this general area.

**Comment by JanimeSenpai** [comment]
Thanks for your response. This library is amazing. Once I came across it, I wanted to create something with it.

**Comment by patrickmichalik** [comment]
You’re welcome! Thanks for the kind words.
