### ISSUE TITLE
How to set different targetVerticalAxisPosition for grouped columns in a chart?

### ISSUE THREAD

**Issue by hhpettersen** [patrykandpatrick/vico#218]
![image](https://user-images.githubusercontent.com/52321453/226316208-9a6afc6d-33eb-42fb-812a-d7526f3168a1.png)

Is it possible to define the `targetVerticalAxisPosition` of grouped columns? Specifically, I would like to set the `targetVerticalAxisPosition` for `entries1` to `AxisPosition.Vertical.End` and for `entries2` to `AxisPosition.Vertical.Start`.

```
val entries1 = entriesOf(4f, 3f, 4f, 4f, 3f, 12f, 2f)
val entries2 = entriesOf(30f, 24f, 27f, 28f, 22f, 54f, 8f)
val entryModel = entryModelOf(entries1, entries2)

ProvideChartStyle(rememberChartStyle(chartColors = chartColors)) {
    Chart(
        modifier = Modifier.background(Color.White),
        chart = columnChart(
            targetVerticalAxisPosition = AxisPosition.Vertical.End
        ),
        model = entryModel,
        startAxis = startAxis(),
        endAxis = endAxis(),
        bottomAxis = bottomAxis(),
    )
}
```

**Comment by patrickmichalik** [comment]
Hello! Unfortunately, there’s no such option at the moment. Such independence is possible only between separate charts that are included in a `ComposedChart`.
