### ISSUE TITLE
Text color in Marker is not updated

### ISSUE THREAD

**Issue by Maliotis** [patrykandpatrick/vico#219]
**Describe the bug**
Updating the textComponent(color = ) parameter is not updating the text color of the label on the Marker
It seems to be copying the lineColor and can't be changed.
If there is way to do this could you please point me to the solution?

**Module**

- [x] `compose`
- [ ] `views`
- [x] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![Screenshot_20230322_101220](https://user-images.githubusercontent.com/30529446/226933679-0e1b711f-2783-4d09-8d59-74975dfdc15f.png)

**Android versions**
Android 13

**Additional context**
version of lib 1.6.4

**Comment by patrickmichalik** [comment]
Hello! This behavior is expected, but you can change it. Please see issue #183 for more information.
