### ISSUE TITLE
Where should I specify the label count? I can only see maxlabelcount inside startaxis. Thanks

### ISSUE THREAD

**Issue by mikfas** [patrykandpatrick/vico#220]
Where should I specify the label count? I can only see maxlabelcount inside startaxis. Thanks

_Originally posted by @mikfas in https://github.com/patrykandpatrick/vico/issues/194#issuecomment-1481149998_

**Comment by patrickmichalik** [comment]
I’ll be closing this issue because it’s a duplicate of your comment under issue #194. I’ve responded there.
