### ISSUE TITLE
Scale issue using Composed Chart

### ISSUE THREAD

**Issue by IssaMansour** [patrykandpatrick/vico#221]
**Describe the bug**
 Scale of Composed chart using ComposedChartEntryModelProducer looks wrong

**Module**

- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [x] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
I'm trying to create a composed chart using 2 ChartEntryModelProducer using this code, but the scale look different than if I create 2 different charts with each model producer

```
Chart(
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.adaptiveYValues(yFraction = 1f, round = true)
        ),
        chartModelProducer = chartModelProducer1 + chartModelProducer2,
        endAxis = endAxis(
            valueFormatter = { x, _ -> x.toInt().toString() },
            horizontalLabelPosition = VerticalAxis.HorizontalLabelPosition.Inside,
            maxLabelCount = 5
        ),
        chartScrollSpec = rememberChartScrollSpec(isScrollEnabled = false)
    )
```

**Expected behavior**

**Screenshots**
Here a screenshot of what I have:
<img width="415" alt="Screen Shot 2023-03-28 at 9 17 49 PM" src="https://user-images.githubusercontent.com/841028/228561167-b868cd8a-f3a3-4d8a-8779-1f8d1d562cf4.png">

I expect to have the result of both of these charts, with same scale:
<img width="424" alt="Screen Shot 2023-03-29 at 9 42 30 AM" src="https://user-images.githubusercontent.com/841028/228561467-213bd45e-c151-4184-a078-d7233552688a.png">

**Android versions**
Android 12

**Additional context**
Maybe it is not an issue but something I'm doing wrong?

**Comment by patrickmichalik** [comment]
Hello! This is expected. The two data sets have different ranges of _y_ values (595 to 692 vs. 217 to 295), and so the lines are being scaled accordingly. In the two-line chart, the axis applies to both lines equally.
