### ISSUE TITLE
Support step X

### ISSUE THREAD

**Issue by daimonkor** [patrykandpatrick/vico#223]
Hello, please help. I am trying provide date labels at xAxis, but found problem, so small auto step X

```code
fun getRandomEntries() = List(4) {
    FloatEntry(
        (Date().time + it * (1000 * 60 * 60 * 24) * 5000).toFloat(),
        Random(it).nextFloat()
    )
}

private val bottomAxisValueFormatter =
    AxisValueFormatter<AxisPosition.Horizontal.Bottom> { x, _ ->
        val sdf = SimpleDateFormat("dd/MM/yyyy HH:mm:ss", Locale.getDefault())
        sdf.format(x)
    }

//////
 val chartEntryModelProducer = ChartEntryModelProducer(getRandomEntries())
  ProvideChartStyle(m3ChartStyle()) {
      Chart(
          modifier = Modifier.wrapContentSize(),
          chart = columnChart(innerSpacing = 50.dp),
          chartModelProducer = chartEntryModelProducer,
          startAxis = startAxis(),
          bottomAxis =
          bottomAxis(
              valueFormatter = bottomAxisValueFormatter,
              labelRotationDegrees = -75F,
              label = axisLabelComponent(textSize = 8.sp, lineCount = 2, textAlign = Paint.Align.CENTER),
          ),
          marker = rememberMarker()
      )
  }

```
<img width="346" alt="image" src="https://user-images.githubusercontent.com/1993501/229305183-8081b55b-b3ce-4295-b492-fb35fd8a2a9f.png">
Thanks a lot for help

**Comment by patrickmichalik** [comment]
Hello! The _x_ step of a chart is the GCD of its _x_ values. If you’d like the four columns to be displayed right next to each other, please ensure that the _x_ values are, for example, consecutive integers. Please see the example [here](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values).

**Comment by daimonkor** [comment]
Thanks, yes, but please check my generator of values. I have only 4 x integers (timestamp).

**Comment by patrickmichalik** [comment]
The spacing of the _x_ values isn’t uniform, however, which is why you’re seeing empty segments. You’ll need to change the _x_ values. This won’t prevent you from displaying timestamps of your choosing along the bottom axis.

**Comment by daimonkor** [comment]
@patrickmichalik  Thanks a lot for help, it works, I changed to mapping logic and x contains only 1,2,3,4. What is the problem? Why label not wrap?
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1993501/229368561-6359671d-0dce-4461-8638-823f4b309f71.png">

**Comment by patrickmichalik** [comment]
It looks like `HorizontalAxis` doesn’t limit the label height correctly. We’ll look into it. As a workaround, you could add a newline character to the pattern used with `SimpleDateFormat`: `"dd/MM/yyyy\nHH:mm:ss"`.

**Comment by patrickmichalik** [comment]
Hello! Vico 1.6.6 resolves the aforementioned issue. Thanks for the feedback!
