### ISSUE TITLE
Value 0 in Y axis when the graph has positive and negative values not shown

### ISSUE THREAD

**Issue by ampeixoto** [patrykandpatrick/vico#224]
First of all, I want to congratulate the owners and the contributors of this library! I recently discovered it and I am playing with it and it is awesome!

Now the question.

I noticed that it should be possible to support positive and negative values on the same graph: https://github.com/patrykandpatrick/vico/pull/139

However in my case, the 0 line is not drawn, making the graph a bit weird:
![image](https://user-images.githubusercontent.com/6080796/229568400-d753d203-a0f5-4b5e-8f0c-28e18462e5a7.png)

Here is my composable:
```
private val columnCornerRadius = 10.dp
private val axisThickness = 3.dp
private const val MAX_Y_LABEL_COUNT = 7

@Composable
fun HistoryChart(
    modifier: Modifier = Modifier,
    yAxisTitle: String = "Label",
    columnChartColors: List<Color> = listOf(
        Colors.color1,
        Colors.color2,
        Colors.color3
    ),
    historyChartEntryModelProducer: ChartEntryModelProducer,
) {
    ProvideChartStyle(rememberChartStyle(columnChartColors)) {
        val defaultColumns = currentChartStyle.columnChart.columns
        val columnChart = columnChart(
            columns = remember(defaultColumns) {
                defaultColumns.map { defaultColumn ->
                    LineComponent(
                        defaultColumn.color,
                        defaultColumn.thicknessDp,
                        Shapes.roundedCornerShape(columnCornerRadius),
                    )
                }
            },
        )
        Chart(
            chart = remember(columnChart) { columnChart },
            chartModelProducer = historyChartEntryModelProducer,
            modifier = modifier,
            bottomAxis = bottomAxis(
                label = axisLabelComponent(
                    typeface = Typeface.DEFAULT_BOLD
                ),
                axis = axisLineComponent(
                    thickness = axisThickness,
                )
            ),
            startAxis = startAxis(
                title = yAxisTitle,
                titleComponent = textComponent(
                    textSize = MaterialTheme.typography.labelMedium.fontSize,
                    typeface = Typeface.DEFAULT_BOLD,
                ),
                maxLabelCount = MAX_Y_LABEL_COUNT,
                label = axisLabelComponent(
                    typeface = Typeface.DEFAULT_BOLD
                ),
                axis = axisLineComponent(
                    thickness = axisThickness
                )
            ),
            fadingEdges = FadingEdges(),
        )
    }
}

@Composable
private fun rememberChartStyle(
    columnChartColors: List<Color>,
    lineChartColors: List<Color>
): ChartStyle {
    val isSystemInDarkTheme = isSystemInDarkTheme()
    return remember(columnChartColors, lineChartColors, isSystemInDarkTheme) {
        val defaultColors = if (isSystemInDarkTheme) DefaultColors.Dark else DefaultColors.Light
        ChartStyle(
            ChartStyle.Axis(
                axisLabelColor = Color(defaultColors.axisLabelColor),
                axisGuidelineColor = Color(defaultColors.axisGuidelineColor),
                axisLineColor = Color(defaultColors.axisLineColor),
            ),
            ChartStyle.ColumnChart(
                columnChartColors.map { columnChartColor ->
                    LineComponent(
                        columnChartColor.toArgb(),
                        DefaultDimens.COLUMN_WIDTH,
                        Shapes.roundedCornerShape(DefaultDimens.COLUMN_ROUNDNESS_PERCENT),
                    )
                },
            ),
            ChartStyle.LineChart(
                lineChartColors.map { lineChartColor ->
                    LineChart.LineSpec(
                        lineColor = lineChartColor.toArgb(),
                        lineBackgroundShader = DynamicShaders.fromBrush(
                            Brush.verticalGradient(
                                listOf(
                                    lineChartColor.copy(DefaultAlpha.LINE_BACKGROUND_SHADER_START),
                                    lineChartColor.copy(DefaultAlpha.LINE_BACKGROUND_SHADER_END),
                                ),
                            ),
                        ),
                    )
                },
            ),
            ChartStyle.Marker(),
            Color(defaultColors.elevationOverlayColor),
        )
    }
}

@Composable
private fun rememberChartStyle(chartColors: List<Color>) =
    rememberChartStyle(columnChartColors = chartColors, lineChartColors = chartColors)

```

Any idea why the 0 line is not displayed?

**Comment by bryantJB** [comment]
Not part of the team, but have you tried adding `columnChart.addDecoration(myThresholdLine)`?
Where the `myThresholdLine` is a `ThresholdLine` with a `lineComponent` and a `labelComponent`, you can make the label invisible as well if needed by setting the color to Color.transparent and the background to null.

**Comment by Gowsky** [comment]
>Any idea why the 0 line is not displayed?

The y-axis line with the value of `0` is not forced in any way at the moment. The y-axis renderer simply iterates between the lowest and highest value.
I understand that it is expected to always render a line at `0` y-axis value, hence we'll work on it.

**Comment by ampeixoto** [comment]
@bryantJB Thanks for the workaround! For now I will use it like that!

@Gowsky Glad to ear that this lib is being actively maintained and improved :) Keep up the good work.

Any estimation on when this feature would be release? No pressure :)

**Comment by patrickmichalik** [comment]
Thanks for your input, @bryantJB. Regarding your question, @ampeixoto, because Vico is a FOSS project that we build in our free time, we’re unable to provide timelines for most changes.

**Comment by p-fischer** [comment]
My workaround doesn't involve a threshold line but aims to draw labels at 0 and at "round numbers" - which imho is a common thing for labels.

E.g. in the screenshot, the biggest value in the chart (which is not visible in the screenshot) seems to be `19.52`and the smallest is `-9.48`.
In this case, I'd use labels from `-10` to `20` and choose the label count in a way so a label is drawn at `0`.

I wrote an algorithm, which has the following input:
- a max label count
- the y-range of the entries

the output is 
- the y-range of the labels (which is slightly bigger than the y-range of the labels)
- a new label count (which is less or equal than the max label count input)

Passing these values to the chart:

- The label count is set via the `startAxis` parameter in the `Chart` constructor (`maxLabelCount`)
- The min and max label (referred to as `yRangeLabels` in the code snippet below) can be set by using a `Chart` constructor variant, which has a `model` parameter. You need to by-pass `ChartEntryModelProducer` and directly create a `ChartEntryModel` like this:
   ```
   private fun chartEntryModel(
          entries: List<List<FloatEntry>>,
          xRange: ClosedRange<Float>,
          xStep: Float,
          yRangeSingleEntries: ClosedRange<Float>,
          yRangeLabels: ClosedRange<Float>,
      ) = object : ChartEntryModel {
          override val entries: List<List<ChartEntry>> = entries
          override val minX: Float = xRange.start
          override val maxX: Float = xRange.endInclusive
          override val minY: Float = yRangeSingleEntries.start
          override val maxY: Float = yRangeSingleEntries.endInclusive
          override val stackedPositiveY: Float = yRangeLabels.endInclusive
          override val stackedNegativeY: Float = yRangeLabels.start
          override val stepX: Float = xStep
      }
   ```

**Comment by patrickmichalik** [comment]
Starting with [Vico 1.9.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.9.0), `VerticalAxis` instances will always label zero if it’s visible. Thanks for your input, @p-fischer!

**Comment by patrickmichalik** [comment]
I wanted to share a note and an update, @p-fischer:

1. I missed this previously, for which I apologize, but in the snippet above, the custom `ChartEntryModel` implementation appears to be unnecessary. There’s a dedicated API for customizing `Chart`s’ _x_ and _y_ ranges: `AxisValuesOverrider`. This API is compatible with `ChartEntryModelProducer`. In Vico 2, it’s called `AxisValueOverrider`.
2. [Vico 2.0.0 Alpha 9](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.9) introduces two new `VerticalAxis` APIs: `AxisItemPlacer.Vertical.step` and `AxisValueOverrider.auto`. You can use these to ensure that `VerticalAxis` instances display round values, among other things. Please see the release notes for more information. `AxisValueOverrider.auto` determines the rounding degree automatically, but we plan on making its behavior customizable. In the meantime, if more aggressive rounding is required, the `AxisValueOverrider.auto` definition can be copied and modified.
