### ISSUE TITLE
How to have lots of data points being automatically scaled as to avoid scrolling the plot? 

### ISSUE THREAD

**Issue by ultrapoci** [patrykandpatrick/vico#227]
I need to plot a graph which has about a thousand points. Normally, in plot libraries like in Python and Julia, when plotting lots of data, the x axis is automatically scaled in order to fit the data to the screen. I can't find a way to do so in vico. I can reduce the distance in dp between points, but there's a minimum under which I cannot go. The default behaviour is to just have the user scroll the plot in order to see all points.

I've thought about manually filtering out points based on the zoom level (if the plot is zoomed out, show one point every 20, if it is zoomed in show more points, and so on) but it seems to be quite an involved process. 

Also, somewhat related, I couldn't find a way to disable scrolling. There is a `chartScrollSpec` option for `Chart`, and `ChartScrollSpec` does have a boolean variable to disable scrolling but building an instance of `ChartScrollSpec` requires passing also an `AnimationSpec` which I don't know how to construct. It seems a bit unnecessary just to disable scrolling, but I may have missed some more obvious way to do it.

**Comment by patrickmichalik** [comment]
Hello! As you’ve noted, scrolling can be disabled via `ChartScrollSpec`. However, you don’t need to create an instance of this class directly. There’s a `rememberChartScrollSpec` function, and each of its parameters has a default value. Try this:

```kt
rememberChartScrollSpec(isScrollEnabled = false)
```

Once you disable scrolling, the chart should behave as desired.

**Comment by ultrapoci** [comment]
> Hello! As you’ve noted, scrolling can be disabled via `ChartScrollSpec`. However, you don’t need to create an instance of this class directly. There’s a `rememberChartScrollSpec` function, and each of its parameters has a default value. Try this:
> 
> ```kotlin
> rememberChartScrollSpec(isScrollEnabled = false)
> ```
> 
> Once you disable scrolling, the chart should behave as desired.

That was easier than expected. Thank you. Now everything works as expected, but I'm facing another problem: `bottomAxis` doesn't have a `maxLabelCount` option like `startAxis`, which means that vico tries to show every label and when there are so many points all labels are hidden because they don't fit on the screen. I've tried writing my own `valueFormatter` in order to filter the labels based on the value: something like this:
```kotlin
bottomAxis = bottomAxis(
    valueFormatter = { value, chartValues ->
        if (range.contains(value.toInt())) "ok" else ""
    },
    tickPosition = HorizontalAxis.TickPosition.Center(),
    guideline = null, tick = null
),
```
where `range` contains all integers I want to be shown as labels. The problem is that no matter how many labels I show, they are always hidden (as in, they are shown as an ellipsis `...`). Is there a way to show a few labels when there are many points?

**Comment by patrickmichalik** [comment]
You can specify the label spacing—please see [here](https://patrykandpatrick.com/vico/wiki/axes). If there’s a specific number of labels that you’d like to be displayed, you can set the spacing to the quotient of the entry count and the desired number of labels.

**Comment by ultrapoci** [comment]
Thank you very much, I didn't realize at first that is what the `spacing` option does!
