### ISSUE TITLE
Ability to set colour of gradients of lines of LineCharts programmatically

### ISSUE THREAD

**Issue by Xenon1345** [patrykandpatrick/vico#228]
Currently, to set the colour of a Line in a LineChart programmatically (using the view system), one can access the 3 lineSpecs and edit their values manually:
```kotlin
(binding.chartView.chart!! as LineChart).lines[0].lineColor = Color.RED
``` 
However, this fails to update the gradient/shader:
![Gradient of graphs remaining grey](https://user-images.githubusercontent.com/64515978/230450517-55d2eaf0-b557-4694-837a-7480a9ab28f4.png)

I was browsing the API for a possible field to set the colour of the gradient, but to no avail. Is there perhaps any way at all to change the colour of the gradient to match that of the lineSpec?

**Comment by patrickmichalik** [comment]
Hello! You can apply a custom gradient via [`LineChart.LineSpec#lineBackgroundShader`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart.line/-line-chart/-line-spec/line-background-shader). As can be seen [here](https://github.com/patrykandpatrick/vico/blob/master/vico/views/src/main/java/com/patrykandpatrick/vico/views/theme/ComponentStyleExtensions.kt#L149-L150), during initialization, the gradient colors are derived from the line color (unless the gradient colors are explicitly specified). If you later change the line color, you have to update the gradient manually.

**Comment by Xenon1345** [comment]
Oh, thanks! It works like a charm!
![Working example of coloured LineSpec shaders](https://user-images.githubusercontent.com/64515978/230532413-01916804-10a4-409e-b2fe-7ae39fe1ca04.png)

**Comment by patrickmichalik** [comment]
You’re welcome!
