### ISSUE TITLE
Cannot remove some paddings on LineChart

### ISSUE THREAD

**Issue by mustafatatarhan0** [patrykandpatrick/vico#229]
![vico_padding](https://user-images.githubusercontent.com/112850036/230554827-bd233566-d86c-4871-82e5-c4f656a470ad.png)

How can I remove or set this paddings (marked as red arrow and circle) ?
I didn't see any parameter related to this.

**Comment by patrickmichalik** [comment]
Hello! The padding to the left and right of the line is a product of the point alignment—the points are center-aligned in their segments. Try using `LineChart.PointPosition.Start` instead. At the moment, this leaves an empty segment at the end of the chart, but you can overcome this by using the solution described [here](https://github.com/patrykandpatrick/vico/issues/222#issuecomment-1496267979). Regarding the marker position, you can create a custom `Marker` implementation that positions the bubble as desired. The `MarkerComponent` definition should serve as a good starting point for your class. Please see `MarkerComponent#drawLabel` and `MarkerComponent#drawGuideline`.

**Comment by Pypey85** [comment]
I am having the same issue, my line chart has padding at both start and end. I can't seem to remove it by setting the minX or maxX in the CartesianLayerRangeProvider.fixed.

The solution referenced above seems to be for a previous version as I can't find where to apply HorizontalLayout.FullWidth.

Any help would be greatly appreciated :)

**Comment by Gowsky** [comment]
Hello, @Pypey85. Please see the `addExtremeLabelPadding` parameter of `HorizontalAxis.ItemPlacer.aligned`.

**Comment by Pypey85** [comment]
Thank you for getting back to me. I have set the addExtremeLabelPadding to false, this does indeed remove the padding but squashes all the lines together creating the illusion of solid grey lines. Looks like I will have to play with the spacing to find a sweet spot for optimal viewing.

Thanks again!
