### ISSUE TITLE
Bottom axis not always shown

### ISSUE THREAD

**Issue by DTselikis** [patrykandpatrick/vico#233]
Sometimes the values on the bottom axis are not displayed. I was not able to consistently reproduce the problem but there are cases that the values on bottom axis are not visible on the chart, just like so:
![image](https://user-images.githubusercontent.com/61058636/230713971-b1aba2fe-fd74-42b0-8aa9-b34a8c714669.png)

Here is a screenshot from a breakpoint inside value formatter that shows that there is indeed a string value associated with this axis value.
![image](https://user-images.githubusercontent.com/61058636/230713454-1ecd2575-f213-4c3f-b229-e0bb3f64233d.png)

I use a map to associate each x value with a string and in the valueFormatter I have put a default string in case no association was found. But even on this case, the default string is not showing and there is a blank spot at bottom axis.

Comparing in to the other diagrams that the bottom axis values does show up, I think the vertical grid line is missing completely when this problem show up.
This is an example of a working diagram:
![image](https://user-images.githubusercontent.com/61058636/230714017-aa0abd74-c350-4e06-8bff-7ae4da101e49.png)

I use compose-m3:1.6.4 in combination with ComposeView in a view-based project.
I have tested in API 33 and 29 and the behaviour is the same.

The same chart with other sets of values works as expected:
![image](https://user-images.githubusercontent.com/61058636/230714271-754cc49f-6107-4494-8702-640ce8eb012b.png)

**Comment by daimonkor** [comment]
@DTselikis Hello, I think that you can try rotate labels
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1993501/230718615-541bc3a5-6a5b-4fa9-851e-628aa1b2f0fc.png">

**Comment by DTselikis** [comment]
@daimonkor Thanks for the tip. I am aware of this feature. And although it does solve the problem of the bottom axis value not fitting for long strings, the problem still remains.
![image](https://user-images.githubusercontent.com/61058636/230720330-2288f699-c93d-4eae-afdc-1f404ba103ba.png)

The bottom axis values are not showing:
![image](https://user-images.githubusercontent.com/61058636/230721422-9f46d500-6a36-4acc-abfd-c02c28253220.png)

And as you can see from the first screenshot, the default "sd" value is showing when there isn't a matching value between an entry's x value and bottom axis value. On the second screenshot the default "sd" is not showing either, so it the data is there but for some reason the values are not visible.

**Comment by DTselikis** [comment]
Here is two example chartEntryModel entries that causes the bottom axis values to not appear:

![image](https://user-images.githubusercontent.com/61058636/230722579-419a5a76-7ea9-455a-9cb1-201bdf9fc289.png)

![image](https://user-images.githubusercontent.com/61058636/230722631-08e6d5d3-9363-49cf-a433-fc677bc8cd59.png)

```
FloatEntry(13.0, 0.10553852)
FloatEntry(15.0, 0.10553852) 

FloatEntry(84.0, 0)
FloatEntry(97.0, 0)
```

**Comment by patrickmichalik** [comment]
Hello! Thank you for the bug report. We’ve been able to reproduce this and are making it a top priority to resolve the issue.

**Comment by patrickmichalik** [comment]
Vico 1.6.5, which is now rolling out, resolves this issue. Thanks again for the report!

**Comment by daimonkor** [comment]
@patrickmichalik , @DTselikis  Hello it works at 1.6.5. Thanks
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1993501/230770968-a99a57f6-d265-4753-a2d7-4962dd4671d0.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/1993501/230770988-e414ead9-6891-48f5-ba12-af4b03f67a78.png">

**Comment by patrickmichalik** [comment]
We’ve not yet introduced the fix described [here](https://github.com/patrykandpatrick/vico/issues/223#issuecomment-1493880910), @daimonkor, so this is presumably a lucky coincidence of some sort, but I’m glad you’re no longer facing the problem. I’ll close issue #223 once Vico 1.6.6, which will include the aforementioned fix, is available.
