### ISSUE TITLE
More than 3 LineSpecs for a LineChart

### ISSUE THREAD

**Issue by Xenon1345** [patrykandpatrick/vico#234]
By default, the LineChart supports 3 LineSpecs which apply to each line of the LineChart, which can be set programmatically by modifying `LineChart.lines`. However, if the LineChart has more than 3 lines, the LineChart will apply one of the 3 LineSpecs for each extra line, resulting in the LineSpecs repeating.
![image](https://user-images.githubusercontent.com/64515978/230758290-b969853c-832b-42e2-b976-131ba53b6957.png)
Is it possible to have more than 3 line colours for a single graph, or must we use a ComposedChart to apply more colours programmatically? If the latter, how so?

**Comment by Gowsky** [comment]
Hello @Xenon1345,
 `LineChart.lines` is a `var`, so you can replace it with as many `LineSpec`s as you wish.

**Comment by Xenon1345** [comment]
Wow, I can't believe I didn't try that -- It works like a charm!
![image](https://user-images.githubusercontent.com/64515978/230758986-bd61434c-063e-48e7-9918-f54f4ecd5759.png)
Kudos to you two for developing such a robust chart library and for providing help so promptly :)
