### ISSUE TITLE
modify maximum and minimum y axis values

### ISSUE THREAD

**Issue by JArsham007** [patrykandpatrick/vico#237]
Hello
I have two doubles like 4000 and 1000 and this values are fetched from API. I want to 1000 be the minimum value and show the average numbers between 1000 and 4000 not 0 to 4000 how can I do that in jetpack compose?

**Comment by patrickmichalik** [comment]
Hello! Please see the third paragraph [here](https://patrykandpatrick.com/vico/wiki/chart-types).
