### ISSUE TITLE
pointPosition start first label not visible

### ISSUE THREAD

**Issue by Vu-Frontcell** [patrykandpatrick/vico#240]
Hi, Great work with this library. I'm trying it out to use in my app. 

I don't know if this is intended. But when setting the pointPosition to start and using a custom axis formatter the first label is not visible.

And also the text labels on x axis doesn't seem to be aligned correctly. (E.g. "c" vs "d").

![Screenshot 2023-04-16 at 21 02 52](https://user-images.githubusercontent.com/6650818/232335768-dd9498be-a64f-4f9b-8eaf-ac2a8411ab94.png)

**Comment by Gowsky** [comment]
Hello @Vu-Frontcell, yes, this is intended. There is no actual space for the first x-axis label. It may physically fit in this particular case, but in general, it would be hard to make it work properly for longer labels and horizontal scroll.

Regarding the alignment, it is correct.
![image](https://user-images.githubusercontent.com/14221573/232336741-84b90ecc-94b3-4aa2-8fe9-4e9fa09a12c3.png)

**Comment by Vu-Frontcell** [comment]
Thanks for the clarifications. 

And how will library handle labeling a lot of entries that will not fit on one screen. I have disabled the horizontal scrolling.
I believe it is a bug according to some other reports. Is the intended behaviour that some labels will be visible and some not?

![Screenshot 2023-04-16 at 21 26 33](https://user-images.githubusercontent.com/6650818/232337333-77976f92-bdfe-485a-9624-de583e4d0d20.png)

**Comment by Gowsky** [comment]
The x-axis labels won’t be shown if there is too little space for them. You can reduce the number of ticks by using [`TickPosition.Center`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.axis.horizontal/-horizontal-axis/-tick-position/#-1360930486%2FClasslikes%2F186187275) with custom `spacing` in your bottom axis.

**Comment by patrickmichalik** [comment]
Hello! I wanted to chime in and mention that we’re currently working on changes that will significantly optimize how charts can be adapted to large data sets, making the API both simpler and more flexible—particularly for line charts.

**Comment by patrickmichalik** [comment]
We’ll look into making that possible, @mak1nt0sh.

**Comment by patrickmichalik** [comment]
[Vico 1.7.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.0) introduces the improvements described [here](https://github.com/patrykandpatrick/vico/issues/240#issuecomment-1510472033). Regarding your suggestion, @mak1nt0sh, updates will be shared under issue #190.
