### ISSUE TITLE
Hard to zoom a chart in compose

### ISSUE THREAD

**Issue by ampeixoto** [patrykandpatrick/vico#241]
Hello,

I just noticed that it is quite hard to zoom horizontally into the graph when using compose... Most of the times, I have to try multiple times before I'm able to zoom successfully...

However, with the view system version, it seems to work much better. Works every time!

I can see that behavior even on the sample app, with v1.6.5.

Is it something already known?

**Comment by Gowsky** [comment]
Hello @ampeixoto, thank you for the report. We've identified the problem and we will fix it.

**Comment by ampeixoto** [comment]
Thanks @Gowsky !
