### ISSUE TITLE
Limit the size of the LineChart, so that it does not scroll.

### ISSUE THREAD

**Issue by tchouaffe** [patrykandpatrick/vico#242]
Hello,

how do I get a line chart to be displayed within the width of my screen?
I have a LineChart with dozen of entries and I want the chart to be so compact that all the entries are visible at once.
For now I have to scroll horizontally to see all the values.

Thanks.

**Comment by Gowsky** [comment]
Hello @tchouaffe, please see #227.

**Comment by tchouaffe** [comment]
Thank you so much @Gowsky.
Before I close this issue I would love to know if there is a way to display dots for chart entries.
Thanks in advance

**Comment by patrickmichalik** [comment]
Hello! There is—please see `LineChart.LineSpec#point`.
