### ISSUE TITLE
Not able to scroll line chart with marker

### ISSUE THREAD

**Issue by tchouaffe** [patrykandpatrick/vico#246]
Hi,

In `Compose` have 4 `LineChart `s align in a column with `Marker`s set. I can not longer scroll up and down.
Whenever I touch a chart in order to scroll up or down, the marker is shown.

**Comment by Gowsky** [comment]
Hi @tchouaffe, do you happen to have horizontal scrolling disabled? If so, we are aware of this bug, and it’ll get fixed with #241.

**Comment by tchouaffe** [comment]
Hi @Gowsky , I have indeed horizontal scrolling disabled.
Nice to know that you working on it.

**Comment by Gowsky** [comment]
Please share the code and a preview of what you get.

**Comment by tchouaffe** [comment]
Here the code for the axis value formatter:

`private val bottomAxisValueFormatter =
    AxisValueFormatter<AxisPosition.Horizontal.Bottom> { value, chartValues ->
        val entries = chartValues.chartEntryModel.entries
        if (entries.isEmpty()) {
            ""
        } else if (entries.first().size > 10) {
            val indexStart = 0
            val indexMiddle = entries.first().size.div(2f).roundToInt()
            val indexEnd = entries.first().size - 1
            val indexes = listOf(indexStart, indexMiddle, indexEnd)

            if (indexes.contains(value.toInt())) {
                getAxisValue(value.toInt(), entries = entries.first())
            } else {
                ""
            }
        } else {
            getAxisValue(value.toInt(), entries = entries.first())
        }
    }`

and here the result:
<img width="325" alt="vico-linechart" src="https://user-images.githubusercontent.com/117275844/233564301-0795785d-8df6-4628-8d3d-71c830eac1b5.png">

**Comment by Gowsky** [comment]
We’ve received some reports with similar issues with axis labels. We’ll try to either improve available space resolution or expose an interface that would allow custom handling of axis labels.
In your case, I’d make sure to remove the horizontal padding from the `labelComponent`.

**Comment by patrickmichalik** [comment]
Hello! Vico 1.6.6 resolves the gesture problem. Greater flexibility in positioning `HorizontalAxis` labels has been requested in issue #172, so I’ll be closing this issue.
