### ISSUE TITLE
Is it possible to pass a Double not a Float in the last version of the library because i couldn't do so before. if not can you consider adding it ?

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#247]

**Comment by Gowsky** [comment]
Hello @abderhim, you can use [`entryOf`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.entry/entry-of?query=fun%20entryOf(x:%20Number,%20y:%20Number):%20FloatEntry) to create `ChartEntry` with a `Double` value. You can also create your own subclass of the `ChartEntry`. However the `Double` will be converted to `Float`, as this type is used internally by charts.

**Comment by abderhim** [comment]
then we can't pass Timestamps with ms as X values, because we can't get the exact values when we convert it to Float :(

**Comment by Gowsky** [comment]
A very similar use case is already described in the wiki [here](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values).

**Comment by abderhim** [comment]
that will not cover Timestamps with ms , when converting to Float , data will be lost

**Comment by patrickmichalik** [comment]
Hello! Millisecond-based timestamps are typically whole numbers, and no rounding errors should occur for such values. The first six decimal digits should be accurate too. Unless you require picosecond-level precision, there shouldn’t be an issue.

**Comment by OskarPersson** [comment]
@patrickmichalik How would you represent a millisecond (or second) -based timestamp as a whole number that can be safely converted to a float? See for example [this playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS45LjIyIiwiY29kZSI6ImltcG9ydCBqYXZhLnRpbWUuSW5zdGFudFxuaW1wb3J0IGtvdGxpbi50ZXN0LipcbmltcG9ydCBqYXZhLnRpbWUuTG9jYWxEYXRlVGltZVxuaW1wb3J0IGphdmEudGltZS5ab25lSWRcblxuZnVuIG1haW4oYXJnczogQXJyYXk8U3RyaW5nPikge1xuICAgIHZhbCBsb2NhbERhdGVUaW1lID0gTG9jYWxEYXRlVGltZS5ub3coKVxuICAgIFRocmVhZC5zbGVlcCgxXzAwMClcbiAgICB2YWwgbG9jYWxEYXRlVGltZTIgPSBMb2NhbERhdGVUaW1lLm5vdygpXG4gICAgdmFsIGluc3RhbnQgPSBsb2NhbERhdGVUaW1lLmF0Wm9uZShab25lSWQuc3lzdGVtRGVmYXVsdCgpKS50b0luc3RhbnQoKVxuICAgIHZhbCBpbnN0YW50MiA9IGxvY2FsRGF0ZVRpbWUyLmF0Wm9uZShab25lSWQuc3lzdGVtRGVmYXVsdCgpKS50b0luc3RhbnQoKVxuICAgIHZhbCBtaWxsaXNlY29uZHMgPSBpbnN0YW50LnRvRXBvY2hNaWxsaSgpXG4gICAgdmFsIG1pbGxpc2Vjb25kczIgPSBpbnN0YW50Mi50b0Vwb2NoTWlsbGkoKVxuICAgIHZhbCBmbG9hdFJlcHJlc2VudGF0aW9uID0gbWlsbGlzZWNvbmRzLnRvRmxvYXQoKVxuICAgIHZhbCBmbG9hdFJlcHJlc2VudGF0aW9uMiA9IG1pbGxpc2Vjb25kczIudG9GbG9hdCgpXG4gICAgdmFsIGZsb2F0VG9EYXRlID0gTG9jYWxEYXRlVGltZS5vZkluc3RhbnQoSW5zdGFudC5vZkVwb2NoTWlsbGkoZmxvYXRSZXByZXNlbnRhdGlvbi50b0xvbmcoKSksIFpvbmVJZC5zeXN0ZW1EZWZhdWx0KCkpXG4gICAgdmFsIGZsb2F0VG9EYXRlMiA9IExvY2FsRGF0ZVRpbWUub2ZJbnN0YW50KEluc3RhbnQub2ZFcG9jaE1pbGxpKGZsb2F0UmVwcmVzZW50YXRpb24yLnRvTG9uZygpKSwgWm9uZUlkLnN5c3RlbURlZmF1bHQoKSlcblxuICAgIHByaW50bG4oXCJMb2NhbERhdGVUaW1lOiAkbG9jYWxEYXRlVGltZVwiKVxuICAgIHByaW50bG4oXCJMb2NhbERhdGVUaW1lMjogJGxvY2FsRGF0ZVRpbWUyXCIpXG4gICAgcHJpbnRsbihcIkZsb2F0IFJlcHJlc2VudGF0aW9uOiAkZmxvYXRSZXByZXNlbnRhdGlvblwiKVxuICAgIHByaW50bG4oXCJGbG9hdCBSZXByZXNlbnRhdGlvbjI6ICRmbG9hdFJlcHJlc2VudGF0aW9uMlwiKVxuICAgIHByaW50bG4oXCJGbG9hdCBhcyBMb2NhbERhdGVUaW1lOiAkZmxvYXRUb0RhdGVcIilcbiAgICBwcmludGxuKFwiRmxvYXQgYXMgTG9jYWxEYXRlVGltZSAyOiAkZmxvYXRUb0RhdGUyXCIpXG59IiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiJ9) where we create two LocalDateTime objects ~1 second apart and still end up with the same float.

```kotlin
import java.time.Instant
import kotlin.test.*
import java.time.LocalDateTime
import java.time.ZoneId

fun main(args: Array<String>) {
    val localDateTime = LocalDateTime.now()
    Thread.sleep(1_000)
    val localDateTime2 = LocalDateTime.now()
    val instant = localDateTime.atZone(ZoneId.systemDefault()).toInstant()
    val instant2 = localDateTime2.atZone(ZoneId.systemDefault()).toInstant()
    val milliseconds = instant.toEpochMilli()
    val milliseconds2 = instant2.toEpochMilli()
    val floatRepresentation = milliseconds.toFloat()
    val floatRepresentation2 = milliseconds2.toFloat()
    val floatToDate = LocalDateTime.ofInstant(Instant.ofEpochMilli(floatRepresentation.toLong()), ZoneId.systemDefault())
    val floatToDate2 = LocalDateTime.ofInstant(Instant.ofEpochMilli(floatRepresentation2.toLong()), ZoneId.systemDefault())

    println("LocalDateTime: $localDateTime")
    println("LocalDateTime2: $localDateTime2")
    println("Float Representation: $floatRepresentation")
    println("Float Representation2: $floatRepresentation2")
    println("Float as LocalDateTime: $floatToDate")
    println("Float as LocalDateTime 2: $floatToDate2")
}
```

Output:

```
LocalDateTime: 2024-02-18T13:09:25.668965898
LocalDateTime2: 2024-02-18T13:09:26.669259623
Float Representation: 1.70826177E12
Float Representation2: 1.70826177E12
Float as LocalDateTime: 2024-02-18T13:09:29.216
Float as LocalDateTime 2: 2024-02-18T13:09:29.216
```

**Comment by patrickmichalik** [comment]
It looks like I made a mistake in my previous comment. I apologize. While `Float.MAX_VALUE` is much greater than a normal timestamp, precision problems are, in fact, possible. Not all whole numbers smaller than `Float.MAX_VALUE` can be represented.

We will be switching from `Float` to `Double` in Vico 2. In the meantime, for most use cases, you can transform your _x_ values to avoid precision loss. Could you let me know a bit more about your use case, @OskarPersson? Do you need precision down to the second or down to the millisecond? What is the range of your _x_ values (e.g., several hours, several days, a year)?
