### ISSUE TITLE
ANR ComposedChartView view-system

### ISSUE THREAD

**Issue by Vu-Frontcell** [patrykandpatrick/vico#250]
I can't pin it down to something specific, but when trying to change data it sometimes hangs(ANR) the whole application. 

Have you experience the same thing?

Or I'm doing something wrong.

```
// on data changed
val a = (composedChartView.entryProducer as ComposedChartEntryModelProducer)
                val b = a.chartModelProducers[0] as ChartEntryModelProducer
                b.setEntries(data.columnValues)

                val c = a.chartModelProducers[1] as ChartEntryModelProducer
                c.setEntries(data.lineValues)
```

**Comment by Gowsky** [comment]
Hello @Vu-Frontcell, please use the bug issue template, or at least provide a MRE.

**Comment by patrickmichalik** [comment]
I’ll be closing this as stale. Please feel free to share a minimal reproducible example and reopen the issue. Thanks!
