### ISSUE TITLE
Missing X-auto-zoom for changing number of samples

### ISSUE THREAD

**Issue by Manfredo725** [patrykandpatrick/vico#254]
I'm almost sure the library does support my use-case, but to me it's really not obvious how that can be done.

I have a pretty simple full-screen line-chart. After starting with an empty list of samples I add samples one after the other slowly (about one sample per second).
For a while (e.g. until 25 samples - depending on portrait- or landscape-orientation of my tablet) everything if fine. When a sample is added, the zoom automatically changes to make all the samples fit into the X-space.
But after that (e.g. starting from the 26th sample) the auto-zoom stops. When further samples are added, the zoom stays the same and some samples are not visible. Then I need to pan or zoom (if enabled) manually(!) to make other (or all) samples visible.

That manual interaction is not acceptable. So I tried to zoom programmatically, but haven't found a solution (honestly I'm not very experienced in Kotlin).
I was hoping for some "autoZoom" I can set to true or some "zoomNrOfSamples" I can set to list.size. Or any other simple way to handle that (pretty common) use-case.
But all I found is some "zoom" variable somehow linked to the finger-zoom-gesture, but buried so deep in the code that I can hardly believe that is the preferred way to go.

Maybe you could give me a hint whether and how that can work...

**Comment by patrickmichalik** [comment]
Hello! Turning off scrolling should do the trick. Are you using Vico with Jetpack Compose or the view system?

**Comment by Manfredo725** [comment]
Many thanks (expecially for the super-fast resonse-time)!

I use Compose and can confirm it works as expected with

        myChartView.isZoomEnabled = false
        //myChartView.isHorizontalScrollEnabled = false  //depricated
        myChartView.chartScrollSpec = ChartScrollSpec(false)

The behavior absolutely makes sense!

**Comment by patrickmichalik** [comment]
You’re welcome!
