### ISSUE TITLE
Deprecation of `stepX` in `ChartEntryModel` is not properly reflected

### ISSUE THREAD

**Issue by ampeixoto** [patrykandpatrick/vico#262]
**Describe the bug**
It seems that the deprecation of `stepX` in `ChartEntryModel` is not properly reflected on the version 1.6.6.

**Module**

- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
I have created the following method in one of my unitTest class to help me create some dummy `ChartEntryModel` instances:
```
    private fun createChartEntryModel(minY: Float, maxY: Float): ChartEntryModel {
        return object : ChartEntryModel {
            override val entries: List<List<ChartEntry>> = emptyList()
            override val minX: Float = 0f
            override val maxX: Float = 0f
            override val minY: Float = minY
            override val maxY: Float = maxY
            override val stackedPositiveY: Float = 0f
            override val stackedNegativeY: Float = 0f
            override val stepX: Float = 0f
            @Deprecated("Use stepX instead")
            override val xStep = 0f
        }
    }
```
But then, when I try to run the unit tests, it is returning me a warning with the following message:

> This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details

The tests run locally, but the problem is that my CI pipeline is configured to treat warnings as errors, so the pipeline fails.

Also, the IDE complains that `'xStep' overrides nothing`:
![image](https://github.com/patrykandpatrick/vico/assets/6080796/b310a3aa-45b7-46be-8b6b-4088c9964601)

And if I go to the declaration of `ChartEntryModel` I see that indeed I don't see the field:
![image](https://github.com/patrykandpatrick/vico/assets/6080796/b19119a7-7a28-4d5b-978a-78a21c46dbfc)

If I remove the `override val xStep = 0f`, I get the following error when compiling:
![image](https://github.com/patrykandpatrick/vico/assets/6080796/beea0f77-c801-40e4-9a87-a2ac08c4ef18)

I am using Vico 1.6.6.

**Expected behavior**
Should be able to properly override `ChartEntryModel` properties in unit tests

**Screenshots**
See above

**Comment by ampeixoto** [comment]
Ok, it is working now... After a Gradle Sync (which I am pretty sure I did before as well). And now I see the correct `ChartEntryModel`. 

Not sure what happened (probably gradle stuff).

Sorry for the noise. Closing the ticket.

**Comment by patrickmichalik** [comment]
No worries! I’m glad the problem is resolved.
