### ISSUE TITLE
Tick x-axis spacing with different entries count

### ISSUE THREAD

**Issue by dianastraliciuc** [patrykandpatrick/vico#263]
I have a series of 100 entries, and the x-axis would correspond to one day, which should be divided into 6 labels. If I have 30 entries, the labels tick spacing is bigger than at 100. Is there a way to keep the same spacing size? I want my graphs not to be scrollable.

**Comment by dianastraliciuc** [comment]
Also, is there a way to make the x axis longer than the chart itself? For example, I would have entries, to fit within a day. But the day is not over yet, so I would have entries only until mid day. The x axis would display a step of 2 hours and the line chart would stop at mid day. Could we achieve this?

**Comment by patrickmichalik** [comment]
Hello!

1. To ensure that we’re on the same page, could you provide an example of this change in label spacing? As such, the entry count shouldn’t influence the label spacing.
2. Yes, you can achieve this using `AxisValuesOverrider`—please see [here](https://patrykandpatrick.com/vico/wiki/chart-types).
