### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ber4444** [patrykandpatrick/vico#271]
Can we add some documentation on how to add accessibility to the chart?

Want to have full control of reading order, accessibility labels, etc 

Something along the lines of https://developer.android.com/guide/topics/ui/accessibility/custom-views

**Comment by Gowsky** [comment]
Hello @ber4444, I'm afraid that currently there is no other way for adding the accessibility other than editing the source code yourself.

**Comment by ber4444** [comment]
https://eevis.codes/blog/2023-07-24/more-accessible-graphs-with-jetpack-compose-part-1-adding-content/

This new article just came out on this exact topic

**Comment by ber4444** [comment]
Another recently released charting library does support accessibility: https://github.com/yml-org/YCharts#accessibility-support
