### ISSUE TITLE
[1.6.6] Breaks chart marker drag and hiding of persistent markers 

### ISSUE THREAD

**Issue by mak1nt0sh** [patrykandpatrick/vico#275]
Starting from `com.patrykandpatrick.vico:compose-m3:1.6.6` you can no longer drag the marker when `chartScrollSpec = rememberChartScrollSpec(isScrollEnabled = false)` . Also persistent markers cannot be hidden by tapping again on the marker.

- In version 1.6.5 I used to be able to hold and drag the marker on the line chart which was in one of the pages of `HorizontalPager`. Now it seems that the drag gets consumed by the pager instead of the chart.

Also hiding marker when tapping again seems to be also broken. I used to save the shown marker like this:

```
var persistentMarkers by remember { mutableStateOf(emptyMap<Float, Marker>()) }

 markerVisibilityChangeListener = object : MarkerVisibilityChangeListener {
                override fun onMarkerMoved(
                    marker: Marker,
                    markerEntryModels: List<Marker.EntryModel>
                ) {
                    persistentMarkers = mapOf(markerEntryModels.first().entry.x to marker)
                }

                override fun onMarkerShown(
                    marker: Marker,
                    markerEntryModels: List<Marker.EntryModel>
                ) {
                    val markerXValue = markerEntryModels.first().entry.x

                    persistentMarkers =
                        if (persistentMarkers.containsKey(markerXValue)) emptyMap() else
                            mapOf(markerXValue to marker)
                }
            }

lineChart(
...
persistentMarkers = persistentMarkers,
...
```

It worked perfectly on 1.6.5. You could tap again on the marker and it would hide it and also worked with dragged gesture to change the marker position on drag. I think the previous version had more natural implementation of the gestures. Hope it will be marked as a bug and not a feature and fixed in later updates! Cheers.

**Comment by Gowsky** [comment]
Hello @mak1nt0sh, thank you for your bug report. We were able to reproduce the bug with persistent markers and resolve it.

Regarding drag gestures, in version 1.6.6 we’ve updated `Modifier`s related to touch gestures which resolved #241 and #246. Unfortunately, the feature you’ve mentioned has been broken in result due to the way `Modifier.scrollable` works. Since we don’t want to rewrite the Modifier, as it is a massive piece of code, and we won’t be fixing it now.

**Comment by Gowsky** [comment]
Forking is the only way to go for now.

**Comment by patrickmichalik** [comment]
Hello! [Vico 1.8.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.8.0) improves how gestures are handled. Charts should now behave better in pagers. There is, however, an issue where, when you swipe to switch pages, a marker appears and moves as if a drag gesture were occurring relative to the chart. We’ll continue to work on this.
