### ISSUE TITLE
TextComponent is not colored

### ISSUE THREAD

**Issue by rjspies** [patrykandpatrick/vico#278]
**Describe the bug**
When I create and use a text component for a marker, it is not colored correctly:
```kotlin
    val label = textComponent(
        background = labelBackground,
        lineCount = LabelLineCount,
        padding = labelPadding,
        typeface = typeface,
        color = Color.Magenta
    )
```
I can see that `TextComponent` is not using its `color` property looking into its `drawText` method.

**Module**

- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**Expected behavior**
The label in the marker is colored in magenta.

**Screenshots**
<img width="366" alt="Screenshot 2023-06-08 at 21 43 34" src="https://github.com/patrykandpatrick/vico/assets/121790537/967a4e8f-4a17-4478-b6ed-277442cb12ec">

**Android versions**
13

**Comment by Gowsky** [comment]
Hello, please see [this comment] (https://github.com/patrykandpatrick/vico/issues/183#issuecomment-1413607210), as this issue has been already covered.
