### ISSUE TITLE
How can I change the space between ticks? When I format the bottom axis label as dd/mm. it always shows ... 

### ISSUE THREAD

**Issue by Nghicv** [patrykandpatrick/vico#279]
**Describe the bug**

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Android versions**
Versions of Android where the bug occurs.

**Additional context**

**Comment by Gowsky** [comment]
This is covered in the wiki.
