### ISSUE TITLE
LabelOffset parameter not active in Jetpack

### ISSUE THREAD

**Issue by nextural** [patrykandpatrick/vico#307]
**Describe the bug**

In Jetpack Compose, labelOffset and labelSpacing are not available parameters in bottomAxis. Code in example app succesfully uses these parameters

**Module**

- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
implemented dependencies: core, compose1.6.5 and compose-m3:1.6.5
** For pure Jetpack, do I need all of these ^^ ?

fun bottomAxis doesn't include parameters specified in APi

`   Chart(
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.fixed(
                minX = 1900f,
                maxX = 2150f,
                minY = 450f,
                maxY = 750f
            ),
            spacing = 40.dp

        ),
        model = chartEntryModel,
        startAxis = startAxis(
                        maxLabelCount = 4
        ),
        bottomAxis = bottomAxis(
            // doesn't recognise these parameters??
        labelOffset = 3
        labelSpacing = 1
        ),
        modifier = Modifier
            .padding(20.dp),

    )`

**Expected behavior**

**Screenshots**
![vico error 2](https://github.com/patrykandpatrick/vico/assets/67638194/b643892f-866f-4fcf-934d-61996aaf236c)

**Comment by patrickmichalik** [comment]
Hello! It looks like you’re using an outdated version of Vico. These parameters are recent additions. Upgrading to the latest version of the library should resolve the issue.

**Comment by nextural** [comment]
Hi! Ah thank you - sucessfully updated. Whilst we're here... is it possible to implement a 'max label count' on the x-axis to define the axis independently of the data set similar to how the y-axis is defined?

![Screenshot 2023-07-07 232023](https://github.com/patrykandpatrick/vico/assets/67638194/02b3afb7-9e91-45fd-9894-bc4ae2a437f5)

**Comment by nextural** [comment]
I see I should use getXStep, but I'm struggling to implement it:

```
 modifier = Modifier
            .padding(20.dp),
// how should getXstep be defined?
// getXStep =  ((ChartEntryModel) -> 50f) throws error
        getXStep =  (???) -> 50f)
```

**Comment by patrickmichalik** [comment]
In Kotlin, you create lambdas using curly brackets:

```kotlin
getXStep = { _ -> 50f },
```

About the diagrams above, Vico is generally intended for more conventional charts. Consider the use cases covered by Google Sheets. That is what we’re targeting, more or less. However, you have the option of extending Vico’s classes and creating your own implementations of its interfaces.
