### ISSUE TITLE
Drag gestures stop listening to events after releaing my finger.

### ISSUE THREAD

**Issue by AbdulrahmanB0** [patrykandpatrick/vico#310]
**Describe the bug**
The chart does not detect drag gestures properly in jetpack compose, when I try to drag my finger on the chart for the first time, everything is fine. Once I stop dragging and release my finger, it completely stops listening to the drag events. So, when I try to drag next time, dragging gestures does not work.

**Module**
- [x] `compose`
- [ ] `view`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` 

**To reproduce**
The following code is from the sample app, where I found that the bug exists. I just added the `rememberMarker()` to show the marker and reproduce the bug.
```
@Preview("Line Chart Expanded", widthDp = 200,  showBackground = true)
@Composable
public fun RegularLineChartExpanded() {
    Chart(
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.fixed(
                minY = -1f,
                maxY = 5f,
            ),
        ),
        model = model1,
        startAxis = startAxis(),
        marker = rememberMarker()
    )
}
```

**Expected behavior**
I expect the drag gestures to not stop listening, and be able to drag again without any problem.

**Android versions**
The bug occurs on Android 13, but I am not sure if it is for older versions.

**Comment by Gowsky** [comment]
Hi @AbdulrahmanB0, please see [this comment](https://github.com/patrykandpatrick/vico/issues/275#issuecomment-1581505047) for an explanation why scrolling behaves this way.

**Comment by patrickmichalik** [comment]
Hello! [Vico 1.8.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.8.0) improves how gestures are handled. You should find that markers now respond to drag gestures as expected. Cheers!
