### ISSUE TITLE
Two points are shown with curved line instead of straight line

### ISSUE THREAD

**Issue by thedipsy** [patrykandpatrick/vico#322]
I have a non-scrollable chart with full width. I have tested the chart with only two points, and the line is curved, but I expect it to be straight. Is there an option to  choose how it is presented?
By the way works good with a lot of points.

What I expect:
<img width="250" alt="Screenshot 2023-07-31 at 09 46 43" src="https://github.com/patrykandpatrick/vico/assets/78094045/7cb1be84-477a-4f06-8cfc-8761a77cdd1f">

What I get:
<img width="250" alt="Screenshot 2023-07-31 at 09 47 34" src="https://github.com/patrykandpatrick/vico/assets/78094045/3f412b53-5228-413b-9922-aa0710661682">

**Comment by makaronis** [comment]
I think you should implement LineChart.LineSpec.PointConnector(look for DefaultPointConnector) and put it in ` lines: List<LineSpec>` param in lineChart() function

**Comment by thedipsy** [comment]
> I think you should implement LineChart.LineSpec.PointConnector(look for DefaultPointConnector) and put it in ` lines: List<LineSpec>` param in lineChart() function

Passing `cubicStrength = 0f` to the `DefaultPointConnector` solved the issue.
Thank you!

**Comment by patrickmichalik** [comment]
Hello! I’m glad you’ve found a solution. Thanks for helping out here, @makaronis!
