### ISSUE TITLE
Year axis labels not visible

### ISSUE THREAD

**Issue by savvasdalkitsis** [patrykandpatrick/vico#340]
**Describe the bug**
I am trying to display a chart with the bottom axis being years (between 1990-2023) rotated 90 degrees

When i use the full year value (say 2012) for the axis, the labels do not show. If i remove 2000 from the years, moving them into the range of -10-23, they do show up but somehow they only render on the left half side of the axis.

I have made sure the axis has enough vertical space to display the labels and that hasn't fixed it.

See a video of the issue wiuth the trimmed years and the code i am using for the chart.

**Module**

- [ ] `compose`
- [ ] `views`
- [x] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

https://github.com/patrykandpatrick/vico/assets/873077/a73c248e-527c-4bb8-8fd9-f6753a66b534

```kotlin
val model = remember(state.mediaByYear) {
    ChartEntryModelProducer(state.mediaByYear.map { FloatEntry(it.key.toFloat(), it.value.toFloat()) })
}
ProvideChartStyle(m2ChartStyle()) {
    Chart(
        modifier = Modifier
            .fillMaxWidth()
            .sizeIn(minHeight = 240.dp),
        chart = columnChart(
            spacing = 3.dp,
        ),
        chartModelProducer = model,
        chartScrollSpec = rememberChartScrollSpec(
            initialScroll = InitialScroll.End
        ),
        marker = markerComponent(
            label = textComponent(),
            indicator = shapeComponent(),
            guideline = lineComponent(color = MaterialTheme.colors.onBackground.copy(alpha = 0.8f)),
        ),
        startAxis = startAxis(
            valueFormatter = { v, _ -> v.toInt().toString() }
        ),
        bottomAxis = bottomAxis(
            title = stringResource(string.year),
            titleComponent = axisLabelComponent(),
            valueFormatter = { v, _ -> v.toInt().toString() },
            labelRotationDegrees = 90f,
            sizeConstraint = Axis.SizeConstraint.Exact(120f),
            label = axisLabelComponent(textSize = 8.sp),
        ),
        isZoomEnabled = true,
        getXStep = { 1f },
        runInitialAnimation = true,
    )
}
```

**Comment by savvasdalkitsis** [comment]
Thanks for the fast response.

I'm using:
com.patrykandpatrick.vico:compose-m2:1.8.0

**Comment by savvasdalkitsis** [comment]
I did some more testing and it looks like the problem with the dates being cut off in the left half only happens when i subtract 2000 from the dates, leading to negative values in the range. When i subtrack 1990, they render ok:

![Screenshot_20230807_173019](https://github.com/patrykandpatrick/vico/assets/873077/33f8b55d-add5-4899-80d9-a9eeaec37598)

So it looks like the first issue is to due with negative values in the bottom axis.

The missing dates is my main problem here as there would be no negative values in my particular example if that was fixed but I guess that's a bug that should be fixed regardless

**Comment by patrickmichalik** [comment]
[Vico 1.9.1](https://github.com/patrykandpatrick/vico/releases/tag/v1.9.1), which resolves this issue, is now rolling out. Cheers!

**Comment by savvasdalkitsis** [comment]
Both scenarios now work perfectly:

![Screenshot_20230807_200552](https://github.com/patrykandpatrick/vico/assets/873077/74378eff-3922-4512-8595-8bc0f6b8ec56)
![Screenshot_20230807_200718](https://github.com/patrykandpatrick/vico/assets/873077/f51a9447-995e-4cd7-be66-1f625e225f50)


Thank you for the fast fix :D

**Comment by patrickmichalik** [comment]
I’m glad to hear that. Thank you for letting us know about the issue!
