### ISSUE TITLE
AxisValuesOverrider causes incorrect start-axis values 

### ISSUE THREAD

**Issue by coalacorey** [patrykandpatrick/vico#346]
**Describe the bug**
Using AxisValuesOverrider.adaptiveYValues() with few values ( < 5) is causing the start axis to move below the bottom axis in certain cases.

**Module**

- [X ] `compose`
- [X ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Set `GENERATOR_X_RANGE_TOP = 3` in the `ShowcaseViewmodel.kt` of the sample app.
Build and run the app, the visual bug can be seen in the third sample chart (second on the screenshot), for both Compose and Views.

**Expected behavior**
The guidelines should show up correctly i.e. they should span the full start-axis and not move below the bottom axis.

**Screenshots**
![Screenshot_20230808-163232](https://github.com/patrykandpatrick/vico/assets/8568609/ac6eb6fb-3b8b-4099-92f3-31bbcd18f612)

**Android versions**
Android 13

**Additional context**
This didn't happen in previous versions, I've upgraded from 1.6.6 to 1.9.1

**Comment by patrickmichalik** [comment]
Hello! Thanks for the bug report. [Vico 1.9.2](https://github.com/patrykandpatrick/vico/releases/tag/v1.9.2), which is now rolling out, resolves this issue.

**Comment by coalacorey** [comment]
You are amazing, thanks!

**Comment by patrickmichalik** [comment]
Thanks again for the report!
