### ISSUE TITLE
Texts are too small in Version 1.10.0

### ISSUE THREAD

**Issue by p-fischer** [patrykandpatrick/vico#364]
**Describe the bug**
Starting from 1.10.0 all texts in the chart (labels, marker texts, etc...) appear to be much smaller.
In the code, 12sp is defined as default text size. It seems the texts are much smaller than 12sp in version 1.10.0

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Open the vico sample app and compare versions 1.9.2 and 1.10.0

**Expected behavior**
The `textSize` argument is respected (e.g. default value 12sp)

**Screenshots**
Version 1.9.2
![image](https://github.com/patrykandpatrick/vico/assets/8547316/477b561a-3f1f-4853-912a-9ca02fd2d480)

Version 1.10.0
![image](https://github.com/patrykandpatrick/vico/assets/8547316/90584811-6245-4c5f-b125-e09a6c220b99)

**Android versions**
Tested with Android 13

**Comment by patrickmichalik** [comment]
Thanks for the report! [Vico 1.10.1](https://github.com/patrykandpatrick/vico/releases/tag/v1.10.1) resolves this issue.
