### ISSUE TITLE
Link to the Wiki is not working

### ISSUE THREAD

**Issue by atick-faisal** [patrykandpatrick/vico#367]
**Describe the bug**
The link to the Wiki and Setup Guide in README.md is broken

**Comment by patrickmichalik** [comment]
Hello! The links seem to work on my end. Could you describe what happens when you click one of them? What link appears in the browser address bar?

**Comment by atick-faisal** [comment]
It is working now. I don't know what the issue was. It was showing the requested page did not exist.

**Comment by patrickmichalik** [comment]
Gotcha. I’m glad you’re no longer facing the problem.
