### ISSUE TITLE
Using a ChartEntryModelProducer breaks Compose preview

### ISSUE THREAD

**Issue by Rosomack** [patrykandpatrick/vico#369]
**Describe the bug**

When using a `ChartEntryModelProducer` charts do not render at all in the Compose preview (they do take up space though). The chart renders fine on a device.

It also works fine when providing an entry model instead.

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Steps to reproduce the behavior.

1. Create a `ChartEntryModelProducer` instantiating it with the preview data
2. Create a chart using this `ChartEntryModelProducer`
3. Create a compose preview for the above
4. Chart does not render in the preview

**Expected behavior**

Chart preview should render in the preview.

**Screenshots**

**Android versions**
Versions of Android where the bug occurs.

Android Studio Giraffe | 2022.3.1

**Additional context**

**Comment by Leedwon** [comment]
Hi, I think you can create preview with `Chart` and `ChartEntryModelProducer`. I'm using Vico 1.9.2 and the following code works for me:
```Kotlin
@Composable
private fun Chart(
    chartEntryModelProducer: ChartEntryModelProducer
) {
    ProvideChartStyle(rememberChartStyle()) {
        Chart(
            chart = lineChart(),
            chartModelProducer = chartEntryModelProducer,
            startAxis = rememberStartAxis(),
            bottomAxis = rememberBottomAxis(guideline = null),
            runInitialAnimation = false
        )
    }
}

@Composable
@Preview
private fun Preview() {
    Surface {
        Chart(
            ChartEntryModelProducer(
                listOf(
                    FloatEntry(0.0f, 0.0f),
                    FloatEntry(1.0f, 2.0f),
                    FloatEntry(2.0f, 3.0f),
                    FloatEntry(3.0f, 4.0f),
                    FloatEntry(4.0f, 5.0f),
                )
            )
        )
    }
}
```

I'm able to see the following preview:
![preview_vico](https://github.com/patrykandpatrick/vico/assets/29312085/bd2014ca-b145-445c-9d3f-35d413b24098)

**Comment by Rosomack** [comment]
@Leedwon Thanks, I couldn't find this as I was on an earlier version of the library. Appreciate the help!

In case it helps anyone you can use 

`runInitialAnimation = !LocalInspectionMode.current`

to only disable the animation for Compose previews - as per [the documentation](https://developer.android.com/jetpack/compose/tooling/previews).

**Comment by patrickmichalik** [comment]
Hello! Thank you for your input, @Leedwon. I’m glad a solution has been found. We’ll be looking into whether we can make it the default for initial animations to be turned off in previews. It’d be preferable for this not to affect interactive previews, so the question is whether we can detect what kind of preview is being used.

**Comment by patrickmichalik** [comment]
Starting with [Vico 1.12.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.12.0), initial animations are no longer run in previews. Thanks for contributing, @Leedwon!
