### ISSUE TITLE
Blank space above and below the chart

### ISSUE THREAD

**Issue by rezafaraji93** [patrykandpatrick/vico#380]
After upgrading to 1.11 I found blank space on top and bottom of the chart.
![Screenshot 2023-08-31 at 12 36 36 PM](https://github.com/patrykandpatrick/vico/assets/71515156/0215bcd4-76b6-420e-b625-aac2e78520a9)

this is my modifier of the chart:
`modifier = Modifier.height(dimens.standard320).background(Color.LightGray)`

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. Since this isn’t a universal problem—it doesn’t occur in the sample app, for example—could you please let us know how to reproduce it? A minimal reproducible example or a list of steps will work. In the future, please use the “Bug report” issue template. Cheers!

**Comment by p-fischer** [comment]
I noticed this too when upgrading from 1.10.1 to 1.11.0.
It seems that the chart now reserves space for the marker. Before, the marker was drawn above the chart.
Not sure, if this behavioral change was intended.

**Comment by patrickmichalik** [comment]
It’s always been the expected behavior for space to be made for `Marker`s, @p-fisher. I’ve compared the two Vico versions that you’ve mentioned and haven’t been able to spot any differences in this respect. Could you share some more information on your setup?

**Comment by p-fischer** [comment]
In my project I'm using markers with multiple lines of text.

To reproduce with the vico sample app:
1. Open `Marker.kt`
2. In line 104 set `private const val LABEL_LINE_COUNT = 10`

Compare versions 1.10.1 and 1.11.0.

Screenshot of 1.10.1:
![image](https://github.com/patrykandpatrick/vico/assets/8547316/5609893b-ac29-47a1-b078-882d270e4ada)

Screenshot of 1.11.0:
![image](https://github.com/patrykandpatrick/vico/assets/8547316/e41cd98d-0e35-40b0-9ea1-261cb5a8fc18)

I'm not sure what behavior I'd expect.
The behavior of 1.11.0 seems more logical but in my case it would be ideal to have the behavior of 1.11.0 but also have a parameter in dp of how much the marker is allowed to go beyond the chart composable. 
Somewhat like this:
`markerAboveChart: Dp = 0.dp,`

**Comment by patrickmichalik** [comment]
Thanks, @p-fisher! We’ve recently resolved an issue where `TextComponent#lineCount` failed to be considered in some instances, and this is a result of that change. We can’t exactly draw outside of the bounds of the top-level elements, as this could lead to clipping, unwanted overlaps, etc. Also, while Compose seems to let us do this, I’m not sure if such drawing is possible in the view system. By default, at least, whatever a view draws seems to be clipped to its bounds. Please keep in mind that the top-level elements are resizable, so if your chart becomes too small once space is made for its `Marker`, you can make the top-level element larger. In the future, we’ll be looking into adding a feature that draws `Marker`s in separate `Window`s (see Compose’s [`Popup`](https://developer.android.com/reference/kotlin/androidx/compose/ui/window/package-summary#Popup(androidx.compose.ui.window.PopupPositionProvider,kotlin.Function0,androidx.compose.ui.window.PopupProperties,kotlin.Function0))). `Marker`s will then not have to request any insets.

**Comment by p-fischer** [comment]
@patrickmichalik Sounds like a really good plan. I think showing markers using popups is a very good fit.

**Comment by zoltish** [comment]
POPUP! 😃

**Comment by rezafaraji93** [comment]
Thanks for your replies, But I couldn't understand that you have planned to fix this issue or not?

**Comment by patrickmichalik** [comment]
Please see my first comment, @rezafaraji93. Once you’ve provided sufficient information for us to reproduce the behavior that you’re seeing, we’ll take a look and share our findings. It’s likely that there’s a connection between this behavior and what @p-fisher and I have been talking about, but there might be more to it.

**Comment by rezafaraji93** [comment]
I used custom marker component, then changing the inset value in marker component solved my problem.
