### ISSUE TITLE
Median marker text is not colored

### ISSUE THREAD

**Issue by p-fischer** [patrykandpatrick/vico#381]
**Describe the bug**
Text coloring doesn't work for the marker at the median x value.

**Affected library version**
The bug was introduced in 1.11.0

**Module**
- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [x] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
1. Use the vico sample app.
2. Open `ShowCaseViewModel.kt`
3. Set `GENERATOR_X_RANGE_TOP` to line 79 to `5` (or `9` or `13`)
4. Start app
5. Inspect Chart 1
6. Tap on the median x value. (That's x=2 if in step 3 the max value was set to 5)

Remarks: This only occurs if the chart is filling the whole area, so the x tick is exaclty in the middle of the screen.
The marker is colored correctly if
- the screen is so big, the chart is not centered (on my 10'' device the error only occurs in portrait mode)
- scrolling or zooming is used

**Expected behavior**
Marker text in Chart 1 is colored like the other markers.

**Observed behavior**
All markers are colored correcty - except for the median marker.

**Screenshots**
![image](https://github.com/patrykandpatrick/vico/assets/8547316/5215aac8-bde8-4966-9f5f-639d55de50fc)

**Android versions**
Android 13

**Comment by p-fischer** [comment]
The bug doesn't look severe in the sample app but my scenario is that I'm showing stacked columns and use the marker text to show both the stacked values and the legend in the marker and for the legend I'm using the chart colors.

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll release a hotfix within 24 hours.

**Comment by patrickmichalik** [comment]
[Vico 1.11.3](https://github.com/patrykandpatrick/vico/releases/tag/v1.11.3), which resolves this, is now rolling out. Cheers!
