### ISSUE TITLE
Crash when using Material 3 version 1.2.*

### ISSUE THREAD

**Issue by Leyonad** [patrykandpatrick/vico#393]
**Describe the bug**
The app will crash when using either of the following dependencies with versions higher than 1.1.1:
dependencies {
    // Material 3
    implementation("androidx.compose.material3:material3:1.2.0-alpha07")
    implementation("androidx.compose.material3:material3-window-size-class:1.2.0-alpha07")
}

Error message: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
at ...
...Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt"

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [x] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
To reproduce the issue, use either of these dependencies:
implementation("androidx.compose.material3:material3:1.2.0-alpha07")
implementation("androidx.compose.material3:material3-window-size-class:1.2.0-alpha07")

**Expected behavior**
I expect the app not to crash.

**Android versions**
Android 13 ("Tiramisu"), API Level 33

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. This isn’t a bug in Vico, but rather a result of breaking changes in Jetpack Compose. We use the latest stable releases of the Compose libraries. Unfortunately, we have no way of guaranteeing compatibility with future releases, and neither would it be optimal for stable Vico versions to depend on unstable library versions. For Vico to work, you’ll have to downgrade your dependencies. As new stable releases of the Compose libraries are made available, we’ll update these libraries in Vico.

**Comment by Leyonad** [comment]
Thanks for the answer.

**Comment by patrickmichalik** [comment]
You’re welcome!
