### ISSUE TITLE
Label color doesn't change when applying TextComponent builder

### ISSUE THREAD

**Issue by theuniking** [patrykandpatrick/vico#395]
**Describe the bug**

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Android versions**
Versions of Android where the bug occurs.

**Additional context**

**Comment by patrickmichalik** [comment]
Hello! Please fill out the issue template—it looks like you’ve left all sections but one empty. Because the bug report is incomplete, I’ll be closing the issue, but please feel free to reopen it once you’ve provided the required information. Thanks!

**Comment by patrickmichalik** [comment]
If the label in question is a `Marker` label, this behavior is expected but can be changed. Please see issue #183 for information on how to achieve the desired result.
