### ISSUE TITLE
Basic examples has error

### ISSUE THREAD

**Issue by klaaslusterbroodvan** [patrykandpatrick/vico#397]
**Describe the bug**
In the basic examples, the following line is listed:

fun getRandomEntries() = List(4) { FloatEntry(it, (0f..16f).random()) }

This function does not work in the most up to date version. The error messages are about "it", where Android studio says "Type mismatch", required Float but found Int. And the function "random()" is an unresolved function.

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ve corrected the error.
