### ISSUE TITLE
unable to add ChartModelProducer<ChartEntryModel> 

### ISSUE THREAD

**Issue by ahmed2146** [patrykandpatrick/vico#442]
### How to reproduce

val chartEntryModelProducer1 = ChartEntryModelProducer(myNumber)
    val chartEntryModelProducer2 = ChartEntryModelProducer(otherNumber)
    val barGraphData:ChartModelProducer<ChartEntryModel> = chartEntryModelProducer1 + chartEntryModelProducer2

error in "+" 

### Observed behavior

Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public operator fun <Model : ChartEntryModel> TypeVariable(Model).plus(other: TypeVariable(Model)): ComposedChartEntryModel<ChartEntryModel> defined in com.patrykandpatrick.vico.core.entry.composed

### Expected behavior

this behavior is observed after 
implementation 'com.patrykandpatrick.vico:compose-m3:1.9.2'
    implementation 'com.patrykandpatrick.vico:core:1.9.2'
    these versions 

### Vico version(s)

Latest stable version, Latest unstable version

### Android version(s)

  implementation 'com.patrykandpatrick.vico:compose-m3:1.13.0-alpha.8'    implementation 'com.patrykandpatrick.vico:core:1.13.0-alpha.8'

**Comment by patrickmichalik** [comment]
Hello! As described in the [the Vico 1.13.0 Alpha 1 release notes](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.1), `ChartEntryModelProducer`s can no longer be combined. This mechanism was intrinsically problematic—it introduced synchronization-related issues. The release notes outline how to use the new `ComposedChartEntryModelProducer`.

**Comment by ahmed2146** [comment]
Thank you so much :)

**Comment by patrickmichalik** [comment]
You’re welcome!
