### ISSUE TITLE
AxisValueFormatter lambda has values not in my list

### ISSUE THREAD

**Issue by spmatthews03** [patrykandpatrick/vico#453]
### How to reproduce

I have the following...
    val horizontalAxisValueFormatter = AxisValueFormatter<AxisPosition.Horizontal.Bottom> { value, _ ->
        xValues[index.toInt()]?.toJavaLocalDateTime()?.format(getFormattedLabel(name)).toString()
    }

where xValues looks like:
![image](https://github.com/patrykandpatrick/vico/assets/10149255/956f2f6e-32de-44a8-a62e-059651d6f6c1)

However, when stepping through the code, the "value" has 3 extra entries in the beginging i.e 0,2.5,5 before any of the keys that my map has. 
Due to these extra my graphs end up with 3 values that were successfully indexed and 3 that were null...
Why is AxisValueFormatter messing with my list before I iterate through it?

### Observed behavior

Added values.

### Expected behavior

No added values

### Vico version(s)

Latest stable version

### Android version(s)

14

**Comment by Gowsky** [comment]
Hi @spmatthews03, Vico calculates the x-axis step dynamically based on a GCD of your entries. It relates to [this comment](https://github.com/patrykandpatrick/vico/issues/452#issuecomment-1791481261).
If it's not the case here, please provide a MRE and reopen the issue.

**Comment by patrickmichalik** [comment]
Hello! To expand on what @Gowsky mentioned, the default `AxisItemPlacer.Horizontal` implementation requests labels for _x_ values such that _x_ = `ChartValues#minX` + (`offset` + _k_) × `ChartValues#xStep`, where _k_ is a natural number. Custom `AxisItemPlacer.Horizontal` implementations can be created, but that shouldn’t be necessary here. With everything correctly configured, you should receive 1 through 6 in the lambda. Generally, the description of the observed behavior appears to be inconsistent with how Vico works. Please provide a complete example. Thanks!
