### ISSUE TITLE
ChartValuesProvider "IllegalStateException"

### ISSUE THREAD

**Issue by Josuhu** [patrykandpatrick/vico#467]
### How to reproduce

Unknown but error seems to ocure during onCreate

### Observed behavior

FATAL Exception crash and app is in a crash loop, Image from the interface and exception is attached

### Expected behavior

???

### Vico version(s)

Latest stable version

### Android version(s)

14

### Additional information

![Exception](https://github.com/patrykandpatrick/vico/assets/55630343/4b129243-3463-4713-a666-3193da6da7ed)

**Comment by Josuhu** [comment]
I would try to solve it somehow but cannot find a away to reach this interface in the Vico API where it is executed.

**Comment by patrickmichalik** [comment]
I’ve tried to reproduce the issue by simulating process death and by repeatedly changing the screen orientation, but I’ve not been able to get a crash to occur. Would you be able to share an example?

**Comment by matheusPereiraG** [comment]
Im also getting this crash and i cannot deterministically reproduce it. The only thing i know of this is that it can occur randomly and mostly when re-populating data onto the graph (Im also using the latest stable version)

**Comment by patrickmichalik** [comment]
Thanks for letting us know, @matheusPereiraG. Are you using Vico with the view system?

**Comment by matheusPereiraG** [comment]
> Thanks for letting us know, @matheusPereiraG. Are you using Vico with the view system?

No, im using jetpack compose.

**Comment by patrickmichalik** [comment]
Thanks, @matheusPereiraG! Unfortunately, we still haven’t been able to reproduce this, whether in Jetpack Compose or in the view system. You’ve mentioned that the crash can occur during data updates. Just to confirm, do these updates coincide with anything notable, such as activity recreation?

**Comment by aleksandra-krzemien** [comment]
I see the same exception, and I prepared a small [demo repo](https://github.com/aleksandra-krzemien/nested-nav-graphs-example/tree/krzemien/vico-illegal-state) (this specific branch). In my case, I have a `ComposeView` and `HorizontalPager` where each page contains a graph. I want to animate graph values with some delay, so I use `ChartEntryModelProducer` and `setEntriesSuspending` with delay. I'm not sure if this is the right way to update entries with delay, so if not, please let me know. However, with current approach the exception occurs pretty often.

Steps to reproduce:
1. Tap button `to second fragment`
2. Swipe between pages left and right
3. At some point the exception is thrown.

It's not thrown at the same moment each time, but eventually it occurred for me every time I tested it.

**Comment by aleksandra-krzemien** [comment]
I found a workaround for the issue (both issues actually) I described above. It seems that the Pager is a part of the issue. If I set entries only when `pageIndex == pagerState?.currentPage` the exception does not occur.

The animation also works just fine, but it makes perfect sense, as Pager loads more items than are actually visible and I want to animate graph only when particular page is shown.

**Comment by patrickmichalik** [comment]
Thanks for the example, @aleksandra-krzemien! We’ve identified the issue. There’s a race condition, so changing when an affected chart’s data is updated (relative to when the chart is created) may prevent the crash from occurring, but generally, this is a bug. We have a fix and will release an update shortly.

Regarding initial animations, that’s exactly right—`HorizontalPager` preloads its pages, and a chart’s initial animation is started when the chart enters composition.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 5](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.5) addresses this. We also plan on releasing a Vico 1 update with a fix.

**Comment by patrickmichalik** [comment]
The aforementioned Vico 1 update, [Vico 1.14.0 Alpha 2](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-alpha.2), is now available.

**Comment by patrickmichalik** [comment]
[Vico 1.14.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0) is rolling out. Cheers!
