### ISSUE TITLE
Chart does not update bar colors properly

### ISSUE THREAD

**Issue by ErickSorto** [patrykandpatrick/vico#511]
### How to reproduce

```
val customColumns = remember {
    barColors.map { color ->
        LineComponent(color = color)
    }
}
val chart = columnChart(
    columns = customColumns,
)

Chart(
    chart = chart,
    chartModelProducer = chartEntryModelProducer,
    startAxis = rememberStartAxis(),
    bottomAxis = bottomAxis,
    marker = MarkerComponent(
        guideline = null,
        indicator = null,
        label = TextComponent.Builder().build(),
    ),
    modifier = Modifier
        .padding(32.dp)
        .height(300.dp),
    isZoomEnabled = false,
)
```

### Observed behavior

All bars end up being the same color as the first item in the list. 

### Expected behavior

Each bar color should have a unique color. 

### Vico version(s)

Latest stable version

### Android version(s)

10

**Comment by Gowsky** [comment]
Hi @ErickSorto, `LineComponent`s are applied per series and not per column, as described in the documentation. But we'll be looking into adding this functionality in the future, as mentioned in #471.
