### ISSUE TITLE
Unexpected background shader when using View Mode in examples Chart 7.

### ISSUE THREAD

**Issue by MacroLens** [patrykandpatrick/vico#518]
### How to reproduce

Looking at the sample code for the latest version [2.0.0-alpha.5](https://patrykandpatrick.com/vico/releases/2.0.0-alpha.5), changing the transaction for the modelProdcer5 to the following:
```kotlin
modelProducer5.tryRunTransaction {
                    add(RandomCartesianModelGenerator.getRandomLineLayerModelPartial(y = -100f..20f, seriesCount = 3))
                }
```
and observing Chart7 we get different versions of the chart depending on the UISystem.

### Observed behavior

When observing with Compose:
![image](https://github.com/patrykandpatrick/vico/assets/54580990/7718c957-4a30-4bd0-babb-8d41956da1ad)
When observing with View:
![image](https://github.com/patrykandpatrick/vico/assets/54580990/ce90901f-c84f-4bf9-b4e8-f079bf587486)

Looks like the background shader in View is still on?

### Expected behavior

The different UI Systems should appear the same.

### Vico version(s)

Latest unstable version

### Android version(s)

Latest SDK Version

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into this.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 6](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.6) addresses this. Cheers!
