### ISSUE TITLE
The library prevents effective minification (by depending on `androidx.compose.ui:ui-tooling`)

### ISSUE THREAD

**Issue by mateuszkwiecinski** [patrykandpatrick/vico#523]
### How to reproduce

The library adds a runtime dependency for a library that isn't meant to be placed in a production/published APK

Related docs:
1. Compose setup, suggestin to put `androidx.compose.ui:ui-tooling` only in developer builds: https://developer.android.com/jetpack/compose/tooling
2. Issue link explaining why this dependency shouldn't be in the production apk: https://issuetracker.google.com/issues/190649014#comment6

How to reproduce? build a minified apk

### Observed behavior

According to gradle:
<img width="531" alt="image" src="https://github.com/patrykandpatrick/vico/assets/36954793/fed67573-24f8-48f5-baa5-39561d3c6741">

to the merged manifest:
![image](https://github.com/patrykandpatrick/vico/assets/36954793/b380518d-f5e1-4e00-9dbd-178f2f556100)

to the source code:
https://github.com/patrykandpatrick/vico/blob/7810af91fdb6f327d8a8263b2a9b3a15d16bb28d/vico/compose/build.gradle#L81C25-L81C41

the `androidx.compose.ui:ui-tooling` is added as a runtime dependency. 

### Expected behavior

Consumers of the library shouldn't need to remember to exclude an unwanted dependecy. The library, most likely should only depend on the tooling api (which is `androidx.compose.ui:ui-tooling-preview` artifact

### Vico version(s)

Latest stable version

### Android version(s)

https://en.wikipedia.org/wiki/Android_version_history

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. This will be resolved in Vico 2.0.0 Alpha 6 and Vico 1.14.0 Alpha 2.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 6](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.6) is now available.

**Comment by patrickmichalik** [comment]
Due to a mistake, this problem wasn’t addressed in [Vico 1.14.0 Alpha 2](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-alpha.2), but it’s been resolved in [Vico 1.14.0 Alpha 3](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-alpha.3). We apologize for the error.

**Comment by patrickmichalik** [comment]
[Vico 1.14.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0) is rolling out. Cheers!
