### ISSUE TITLE
Missing LinearGradientShader for view module

### ISSUE THREAD

**Issue by csbenz** [patrykandpatrick/vico#535]
### How to reproduce

Cannot find
https://github.com/patrykandpatrick/vico/blob/master/vico/compose/src/main/java/com/patrykandpatrick/vico/compose/component/shape/shader/LinearGradientShader.kt

### Observed behavior

It's missing

### Expected behavior

Not missing

### Vico version(s)

Latest stable version

### Android version(s)

Latest

**Comment by Gowsky** [comment]
Hi @csbenz, they are [already there](https://github.com/patrykandpatrick/vico/blob/a02b332cab38a297e2fea2d07924454aef6611eb/vico/views/src/main/java/com/patrykandpatrick/vico/views/component/shape/shader/DynamicShaders.kt#L70), though they are accessible through `DynamicShaders` object.
