### ISSUE TITLE
Not able to see x-axis and y-axis labels in some devices. 

### ISSUE THREAD

**Issue by JainSaloni4** [patrykandpatrick/vico#541]
### How to reproduce

On some devices the x-axis and y-axis labels are not visible in the chart. This is device specific, the labels are getting passed into the chart yet the labels are not visible for both the axis. (Devices: Realme GT2, Samsung S22 ultra)

### Observed behavior

The x-axis and y-axis labels are being passed, but not visible on some on specific devices.

### Expected behavior

The labels for both the devices should be visible in the screen

### Vico version(s)

Latest stable version, Latest unstable version

### Android version(s)

13

### Additional information

Current Version of vico charts used on my end is: 1.6.4

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. Under “Additional information,” you’ve mentioned that you’re using Vico 1.6.4. Just to confirm, have you checked if this issue occurs in Vico 1.13.1, Vico 1.14.0 Alpha 2, or Vico 2.0.0 Alpha 6?

**Comment by JainSaloni4** [comment]
> Hello! Thanks for the report. For “Vico version(s),” you’ve selected “Latest stable version” and “Latest unstable version,” but under “Additional information,” you’ve mentioned that you’re using Vico 1.6.4. Just to confirm, have you checked if this issue occurs in Vico 1.13.1, Vico 1.14.0 Alpha 2, or Vico 2.0.0 Alpha 6?

Not checked on another versions yet.

**Comment by patrickmichalik** [comment]
I’m afraid we’re unable to accept bug reports for outdated Vico versions—the issue may no longer occur in the latest versions, and only if a bug still exists is a report of it actionable. As per the note in the issue template, we’d ask you to check if the problem affects one of the versions listed above. If it does, please reopen this issue.

**Comment by TatjanaDjurdjevic** [comment]
This happens for me too.

I am using Vico 1.14.0 (views and core libraries).

On pixel phone everything works as expected. 

On device Samsung S21, with Android 14 and One UI version 6.0, neither x or y labels are showed.

**Comment by patrickmichalik** [comment]
Hello, @TatjanaDjurdjevic! Could you please share a minimal reproducible example?

**Comment by TatjanaDjurdjevic** [comment]
I have just tried it out on Pixel 7A with Android 14 (device), and also the x and y axes are not showing, but however on emulator on my laptop which is pixel 7A with Android 14 everything works fine. 

Minimal reproducible example:

        val data = listOf("2022-07-01" to 2f, "2022-07-02" to 6f, "2022-07-04" to 4f).associate { (dateString, yValue) ->
            LocalDate.parse(dateString) to yValue
        }
        val xValuesToDates = data.keys.associateBy { it.toEpochDay().toFloat() }
        val chartEntryModel = entryModelOf(xValuesToDates.keys.zip(data.values, ::entryOf))
        val dateTimeFormatter: DateTimeFormatter = DateTimeFormatter.ofPattern("d MMM")
        val horizontalAxisValueFormatter = AxisValueFormatter<AxisPosition.Horizontal.Bottom> { value, _ ->
            (xValuesToDates[value] ?: LocalDate.ofEpochDay(value.toLong())).format(dateTimeFormatter)
        }

        binding.chartViewTest.setModel(chartEntryModel)
        with(binding.chartViewTest) {
            with(bottomAxis as HorizontalAxis) {
                valueFormatter = horizontalAxisValueFormatter
                isZoomEnabled = true
            }
            with(startAxis as VerticalAxis) {
                title = "Test"
                isZoomEnabled = true
                titleComponent = TextComponent.Builder().build()
            }
        }

**Comment by TatjanaDjurdjevic** [comment]
It was my bad.
Actually the problem was dark mode. 
When device is in dark mode, label color is white, and my background is white (app does not support dark mode, and labels were not visible).

**Comment by patrickmichalik** [comment]
Got it, @TatjanaDjurdjevic. I’m glad you’ve found the cause of the issue. Cheers!

**Comment by Kosterio** [comment]
> Got it, [@TatjanaDjurdjevic](https://github.com/TatjanaDjurdjevic). I’m glad you’ve found the cause of the issue. Cheers!

@patrickmichalik I have the same issue, but as for me it should be customizable - which theme will be used on the chart, Light or Dark.
I noticed that `getDefaultColors()` and `vicoTheme` cannot be overridden, so I cannot force set the Light theme.
In the `view` app (`: AppCompatActivity`) I can use the `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)` method as workaround, but in `Compose` app (`: ComponentActivity`) it does not work.

**Comment by Gowsky** [comment]
Hello, @Kosterio.

> I noticed that `getDefaultColors()` and `vicoTheme` cannot be overridden, so I cannot force set the Light theme.

You can. `vicoTheme` is a reference to the `VicoTheme` composition local, which you can easily set to any `VicoTheme` you want by using `ProvideVicoTheme`, as shown in the guide.

The behavior where the colors depend on `isDeviceInDarkMode()` simply corresponds to the default value for that composition local.

Also, while this is not necessary here, it’s worth keeping in mind that you can also apply colors to individual components directly, overriding the theme.

Regarding overriding `getDefaultColors`, it wouldn’t make sense. Customization is using something in place of the default, not modifying the default itself.

**Comment by Kosterio** [comment]
> The behavior where the colors depend on `isDeviceInDarkMode()` simply corresponds to the default value for that composition local.

Yes, but what if I want to give the user a choice of which theme to use - dark or light?
Both of them are in the library, but they are `internal`, so I cannot use they when I want.
Therefore, instead of just using the theme I want, in this case I will need to manually create 2 themes, although they already exist.

**Comment by Gowsky** [comment]
> Yes, but what if I want to give the user a choice of which theme to use - dark or light?

You can still provide the choice by using a custom `VicoTheme` composition local, or by changing the colors of individual components.

> Both of them are in the library, but they are internal, so I cannot use they when I want.
Therefore, instead of just using the theme I want, in this case I will need to manually create 2 themes, although they already exist.

The defaults handle the average case, where the app follows the system theme. Exposing them would pollute the API. Only six colors are needed to instantiate `VicoTheme`, and doing so also makes you think about what colors best match your app. Also, if you’re using a Material theme, you can use `rememberM*VicoTheme` to create a `VicoTheme` based on the current Material theme, which will respect any manual overrides.

**Comment by Kosterio** [comment]
> You can still provide the choice by using a custom `VicoTheme` composition local, or by changing the colors of individual components.

I see some contradiction here.
By default, the theme is living by own life, and it is unexpected that the colors of the chart will change on another system theme.

> Exposing them would pollute the API.

Ok, but the behavior should be expected - either the theme behavior can be selected (dark/light/auto), or there is only one default theme.

**Comment by Gowsky** [comment]
> I see some contradiction here.
By default, the theme is living by own life, and it is unexpected that the colors of the chart will change on another system theme.

There's no contradiction. The default `vicoTheme` composition local uses the default Vico colors that adapt to light and dark modes. If you provide your custom theme using `ProvideVicoTheme` only this theme will be used within the scope of the composition local.

>Ok, but the behavior should be expected - either the theme behavior can be selected (dark/light/auto), or there is only one default theme.

As I mentioned above, there are two options:
- The default theme, which adapts to light and dark modes.
- A custom theme.

The point of the default theme is to give you a head start and make the chart legible in both light and dark modes. You are expected to provide a custom theme (either globally via the composition local, or by modifying individual components) as the default theme won't match most of the apps anyway.
