### ISSUE TITLE
2.0.0-alpha.11 sample app main screen goes blank

### ISSUE THREAD

**Issue by paulirotta** [patrykandpatrick/vico#614]
### How to reproduce

git clone https://github.com/patrykandpatrick/vico
cd vico
git checkout v2.0.0-alpha.11

Build and install to Samsung
Open any chart
Go back to the main screen

### Observed behavior

After displaying for a second, the main screen goes blank

### Expected behavior

Main screen allows another demo to be displayed

### Vico version(s)

Latest unstable version

### Android version(s)

13

**Comment by paulirotta** [comment]
This happened 2 builds in a row. Build-deploy again to see another demo and now it seems to work. No changes to the project since clone. Just weird

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. I’ve been able to reproduce this by tapping the back arrow twice in short succession. It looks like the navigation library doesn’t immediately block interactions with the chart screen when it’s removed from the back stack. `NavController#popBackStack` is called twice, and the back stack is left empty. We’ll add a safeguard.

**Comment by patrickmichalik** [comment]
This should no longer happen in the sample app for [Vico 2.0.0 Alpha 12](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.12). Cheers!
