### ISSUE TITLE
Space above line chart.

### ISSUE THREAD

**Issue by oyugiben** [patrykandpatrick/vico#616]
### How to reproduce

Create a basic line chart. When it is set to fillMaxSize, there is some left over space at the top of the chart.

### Observed behavior

Space left at the top of the line chart, i.e. some padding before the highest point in the chart and the top of the CartesianChartHost.

### Expected behavior

The chart should fit snuggly in the bounds of its containing box.

### Vico version(s)

Latest unstable version

### Android version(s)

11, 12

**Comment by oyugiben** [comment]
Apologies. The space was to accommodate the marker.

**Comment by patrickmichalik** [comment]
Hello! No worries. I’m glad you’ve identified the cause of this behavior. If you’re using `MarkerComponent`, you can set `labelPosition` to `MarkerComponent.LabelPosition.AroundPoint` to prevent any extra insets from being requested. The label will be displayed below the marked point if there isn’t enough room above it.
