### ISSUE TITLE
Marker didn't show "0" value

### ISSUE THREAD

**Issue by ednabueno** [patrykandpatrick/vico#631]
### How to reproduce

I am using Column Cartesian Layer with list of data with 0.0.

### Observed behavior

The chart is smoothly rendered using the view. But when I tap the x-axis/column with 0.00 data, the marker showed above the next or previous column with their corresponding data not in the actual x-axis with 0.00 value

### Expected behavior

The marker must show on the x-axis with 0.00 value

### Vico version(s)

Latest unstable version

### Android version(s)

Android Version 12

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

**Comment by ednabueno** [comment]
Thank you for your response. I already show the 0.00 in the marker, but I need to fake and configure the data from the API that contain 0.00 and change to 0.001, which I think is not good to put an extra code just to configure the columnChart in order to achieve the required UI. 

Or I miss something?

**Comment by patrickmichalik** [comment]
Such a workaround is required in Vico 2.0.0 Alpha 12 and earlier, @ednabueno. We’ve just released [Vico 2.0.0 Alpha 13](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.13), which resolves this problem. Once you’ve updated, you can remove the workaround, and the `Marker` should still show up. Cheers!

**Comment by patrickmichalik** [comment]
Since this still affects Vico 1, which continues to receive bug fixes, I’ll be reopening the issue. The “done in alpha” label signifies that the bug has been resolved in Vico 2. Once it’s fixed in Vico 1 too, we’ll close the issue.

**Comment by patrickmichalik** [comment]
[Vico 1.15.0 Alpha 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0-alpha.1) addresses this.

**Comment by patrickmichalik** [comment]
[Vico 1.15.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0) is now available.
