### ISSUE TITLE
Data Labels for Stacked bar chart have wrong position and value

### ISSUE THREAD

**Issue by marks-kr** [patrykandpatrick/vico#635]
### How to reproduce

Make a bar chart with a single series and a merge mode of Stacked, and data labels set to a position of Top.

I initially saw this problem with a 2-series Stacked bar chart, but found that the labels were the exact same if I replaced them with a single series of their sum.

Attached below is a code snippet that produces the attached graphs with vico 2.0.0 alpha 12
[CodeSnippet.txt](https://github.com/patrykandpatrick/vico/files/14780691/CodeSnippet.txt)

### Observed behavior

Labels are displayed overlapping the bars, and showing values that do not match the vertical axis.
![image](https://github.com/patrykandpatrick/vico/assets/81575527/2c71b865-bda2-452f-afe7-6276550bcfa6)

### Expected behavior

The data labels for a single series should have the same position as a Grouped bar chart.
![image](https://github.com/patrykandpatrick/vico/assets/81575527/daa5e00f-73b7-4a97-b026-57bccfddee78)

### Vico version(s)

Latest unstable version

### Android version(s)

SDK 30

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 13](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.13) fixes this. Cheers!

**Comment by patrickmichalik** [comment]
[Vico 1.15.0 Alpha 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0-alpha.1) addresses this.

**Comment by patrickmichalik** [comment]
[Vico 1.15.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0) is now available.
