### ISSUE TITLE
Marker missing style defined by custom MarkerLabelFormatter

### ISSUE THREAD

**Issue by SebPawp** [patrykandpatrick/vico#638]
### How to reproduce

I pulled the source code and edited the sample chart 3. 
Here is the diff I made

[marker_styling_issue.patch](https://github.com/patrykandpatrick/vico/files/14791332/marker_styling_issue.patch)

### Observed behavior

Looking at the video you can see the Marker in the middle doesn't have any style.
 
https://github.com/patrykandpatrick/vico/assets/129093932/2494fd1f-ea93-43f9-aeeb-574825b5748e

### Expected behavior

Marker in the middle should rendered the same way as the others.

### Vico version(s)

Latest unstable version -> `v2.0.0-alpha.12`

### Android version(s)

Emulator with version 33

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

**Comment by patrickmichalik** [comment]
Thanks, @SebPawp! I’ve been able to reproduce this on a virtual Pixel 6 Pro. I previously used a virtual Pixel 3a, a virtual Pixel 6, and a real Pixel 7, and the problem didn’t occur on any of those devices.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 14](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.14) fixes this. Cheers!

**Comment by SebPawp** [comment]
I confirm, it's working for me with [Vico 2.0.0 Alpha 14](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.14)!
Thank you for the quick fix.

**Comment by patrickmichalik** [comment]
Thanks for confirming. You’re welcome!

**Comment by patrickmichalik** [comment]
[Vico 1.15.0 Alpha 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0-alpha.1) addresses this.

**Comment by patrickmichalik** [comment]
[Vico 1.15.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0) is now available.
