### ISSUE TITLE
Cannot access CartesianChartHost in my project

### ISSUE THREAD

**Issue by puregallery** [patrykandpatrick/vico#639]
### How to reproduce

import vico into an existing app by adding these

  ``` 
    implementation "com.patrykandpatrick.vico:core:1.13.1"
    implementation "com.patrykandpatrick.vico:compose:1.13.1"
    implementation "com.patrykandpatrick.vico:compose-m3:1.13.1"

```

### Observed behavior

Creating graphs similar to sample app is not possible. I had to use
```

    val lineChart = lineChart(
        lines = listOf(
            LineSpec(
                lineThicknessDp = 0.8f,
                lineColor = chartLineColor.toArgb(),
                lineBackgroundShader = DynamicShaders.fromBrush(
                    Brush.verticalGradient(
                        listOf(
                            chartLineColor.copy(0.75f),
                            chartLineColor.copy(0.4f)
                        )
                    )
                )
            )
        ),
    )

    Chart(
        modifier = modifier,
        chart = lineChart,
        model = chartEntryModel,
        startAxis = startAxis,
        bottomAxis = bottomAxis,
        isZoomEnabled = false,
        chartScrollSpec = chartScrollSpec,
        horizontalLayout = HorizontalLayout.FullWidth(),
        marker = marker
    )
```

### Expected behavior

I expected to create charts the same way sample app does

### Vico version(s)

Latest stable version

### Android version(s)

1.13.1

**Comment by Gowsky** [comment]
Hi! If you expect to use the same APIs as the sample app, please make sure to use the same library version. The current master branch is on v2.0.0-alpha.14. Cheers!

**Comment by patrickmichalik** [comment]
Hello! Just to clarify, `master` is a bit beyond version 2.0.0 Alpha 14—we’re working on the next update. For the Vico 2.0.0 Alpha 14 sample app, run `git checkout v2.0.0-alpha.14`. Other versions of the sample app can be accessed analogously.
