### ISSUE TITLE
[View] CartesianChartView always handles touches, even if `isClickable` or `isEnabled` is false

### ISSUE THREAD

**Issue by kroegerama** [patrykandpatrick/vico#693]
### How to reproduce

I have added a `CartesianChartView` with the attributes set:

```xml
app:chartHorizontalScrollingEnabled="false"
app:chartZoomEnabled="false"
```

Currently, there is no way to set a click listener to the View or its parent, because the `onTouchEvent` is overridden in a way that it 
[always returns true](https://github.com/patrykandpatrick/vico/blob/a1383f8f395d667ed8f934aa0b07d1d95e7e4e81/vico/views/src/main/java/com/patrykandpatrick/vico/views/cartesian/CartesianChartView.kt#L306) because of the [`ACTION_DOWN` handler](https://github.com/patrykandpatrick/vico/blob/a1383f8f395d667ed8f934aa0b07d1d95e7e4e81/vico/views/src/main/java/com/patrykandpatrick/vico/views/common/gesture/MotionEventHandler.kt#L63).

Setting these attributes in code did not work as well (as expected):
```kotlin
barChart.isEnabled = false
barChart.isClickable = false
```

### Observed behavior

The `CartesianChartView` is cannot be made clickable (by setting a click listener) and blocks the click event from its parent. Even if all touch events (zoom, scroll) are disabled.

### Expected behavior

The `CartesianChartView` can be set to ignore clicks (transparent for clicks) and allows its own `OnClickListener` to be triggered.

### Vico version(s)

Latest unstable version

### Android version(s)

14

### Additional information

Tested with vico views `v2.0.0-alpha.19`

**Comment by Gowsky** [comment]
Hello @kroegerama, thank you for the report. We'll look into it.

**Comment by Gowsky** [comment]
Hello! The bug has been fixed in Vico 2.0.0-alpha.20. `CartesianChartView` now works with `OnClickListener`s and `OnLongClickListener`s. Also, the view will no longer handle any `MotionEvent`s when `isEnabled == false`.

**Comment by kroegerama** [comment]
Disabling works fine. Thanks a lot! ❤️

**Comment by Gowsky** [comment]
You’re welcome! I'm reopening this issue, as it still needs to be fixed in Vico 1.

**Comment by patrickmichalik** [comment]
[Vico 1.15.0 Alpha 2](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0-alpha.2) addresses this. Cheers!

**Comment by patrickmichalik** [comment]
[Vico 1.15.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.15.0) is now available.
