### ISSUE TITLE
ColumnChart with MergeMode.Grouped does not receive callback for all the series added through CartesianMarkerVisibilityListener

### ISSUE THREAD

**Issue by puregallery** [patrykandpatrick/vico#711]
### How to reproduce

Create a ColumnChart with two series, add a marker and `CartesianMarkerVisibilityListener`. Drag across all the columns/bars

### Observed behavior

We are getting a single callback for both entries in the series.

### Expected behavior

I expect a callback for both the columns...even with the same x value.

### Vico version(s)

alpha19

### Android version(s)

14

**Comment by patrickmichalik** [comment]
Hello! When a stack is marked, a single `CartesianMarker` is shown a single time, and so `CartesianMarkerVisibilityListener#onShown` is called once (which is in agreement with its documentation). However, information on both marked columns is provided. Specifically, `targets` contains one `ColumnCartesianLayerMarkerTarget` with two `ColumnCartesianLayerMarkerTarget.Column`s, one for each column. Each `ColumnCartesianLayerMarkerTarget.Column` contains its corresponding column’s `ColumnCartesianLayerModel.Entry`. You can confirm the number of `ColumnCartesianLayerMarkerTarget.Column`s by evaluating the following:

```kt
(targets[0] as ColumnCartesianLayerMarkerTarget).columns.size
```

I’ll thus be closing this issue. If you have any questions, let me know. Cheers!

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

I previously misread the issue and thought that it referred to expected behavior, leading me to close it. I’ve now reopened the issue. Apologies for the confusion.

**Comment by Gowsky** [comment]
Hello, Vico [2.0.0-alpha.21](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.21) fixes this. Remember to override both `onShown` and `onUpdated` to receive all of the required callbacks.
