### ISSUE TITLE
[TopBottomShader] with negative values splits the line color into two

### ISSUE THREAD

**Issue by mak1nt0sh** [patrykandpatrick/vico#784]
### How to reproduce

Use `LineSpec` with
```
shader = TopBottomShader(
topShader = DynamicShader.color(MaterialTheme.colorScheme.primary),
bottomShader = DynamicShader.color(MaterialTheme.customColors.negative)
)
```

and have postive, negative and zero values in `ySeries`

### Observed behavior

**Zero,Positive & Negative**
<img width="484" alt="Screenshot 2024-07-03 at 13 29 18" src="https://github.com/patrykandpatrick/vico/assets/33786477/7a01b26f-9a9d-4674-88fe-ad174ac3e033">

**Zero & Negative**
<img width="482" alt="Screenshot 2024-07-03 at 13 34 32" src="https://github.com/patrykandpatrick/vico/assets/33786477/95b7ecdb-c7b1-47d5-84f8-b7374083f527">

**Zero & Positive**
<img width="492" alt="Screenshot 2024-07-03 at 13 50 52" src="https://github.com/patrykandpatrick/vico/assets/33786477/7183bdd5-9cb7-48b2-9bc4-f608f0c1d8cd">

### Expected behavior

Zero values should be treated as positive and be drawn using topShader.

### Vico version(s)

2.0.0-alpha.21

### Android version(s)

Any

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 26](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.26) resolves this. Cheers!

**Comment by patrickmichalik** [comment]
I’m reopening this issue because, as reported [here](https://github.com/patrykandpatrick/vico/issues/809#issuecomment-2257690707), the problem now occurs under different circumstances—when the split’s _y_ value is equal or very close to the `LineCartesianLayer`’s minimum _y_ value. We overlooked this edge case while developing the fix, for which we apologize. We’ll look into it.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 27](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.27) addresses the aforementioned oversight. Thanks again!

**Comment by mak1nt0sh** [comment]
Still experiencing same issue on [Vico 2.0.0 Alpha 27](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.27).

![lineissue](https://github.com/user-attachments/assets/20c10a06-d7fd-45c4-b888-ff4c5e755aee)

OLD ISSUE: Line colors are split.
NEW ISSUE: Default marker mixes the colors of both fill colors:

```
fill = LineCartesianLayer.LineFill.double(
                            topFill = fill(MaterialTheme.colorScheme.primary),
                            bottomFill = fill(MaterialTheme.customColors.negative)
                        )
```

Data for this view:

```
xSeries = [19936, 19937, 19938, 19939, 19940, 19941, 19942]
ySeries = [500.00, -5, -5, -5, -5, -25, -25]
```

**Comment by Gowsky** [comment]
Hi @mak1nt0sh, it’s related, but it’s not the same problem. The split position is now calculated correctly, but there seems to be an issue with color extraction, probably due to antialiasing. Please open a new issue that can be a copy of your last comment, or just a link to the comment.
