### ISSUE TITLE
Issue with labels not showing as expected

### ISSUE THREAD

**Issue by findjigar** [patrykandpatrick/vico#787]
### How to reproduce

```
val data = MutableList(size = 31) { 8f }.apply {
  set(2, 6f)
  set(12, 4f)
  set(14, 9f)
}

val labels = MutableList(size = 31) { it.plus(1).toString() }

// Use this to re-create the issue (check the preview below)
val labelsWithEmptyString = MutableList(size = 31) { "" }.apply {
  set(0, "1")
  set(4, "5")
  set(9, "10")
  set(14, "15")
  set(19, "20")
  set(24, "25")
  set(30, "31")
}

fun getFormatter(labels: List<String>) = CartesianValueFormatter { x, _, _ ->
  labels[x.toInt() % labels.size]
}

@Composable
fun MonthlyChart(formatter: CartesianValueFormatter) {
  CartesianChartHost(
    horizontalLayout = HorizontalLayout.FullWidth(
      scalableEndPaddingDp = 0f,
      scalableStartPaddingDp = 0f,
    ),
    chart = rememberCartesianChart(
      rememberColumnCartesianLayer(),
      bottomAxis = rememberBottomAxis(
        itemPlacer = remember {
          AxisItemPlacer.Horizontal.default(addExtremeLabelPadding = true)
        },
        valueFormatter = formatter,
        label = rememberAxisLabelComponent(
          textSize = 12.sp,
          padding = Dimensions.of(0.dp, 0.dp),
          margins = Dimensions.of(0.dp, 0.dp),
        ),
      ),
    ),
    model = CartesianChartModel(ColumnCartesianLayerModel.build { series(data) }),
    scrollState = rememberVicoScrollState(scrollEnabled = false),
  )
}

@Preview(widthDp = 300, heightDp = 200)
@Composable
fun MonthlyChartAllLabels() {
  PreviewSurface {
    MonthlyChart(formatter = getFormatter(labels))
  }
}

@Preview(widthDp = 300, heightDp = 200)
@Composable
fun MonthlyChartLabelsWithEmptyString() {
  PreviewSurface {
    MonthlyChart(formatter = getFormatter(labelsWithEmptyString))
  }
}
```

### Observed behavior

<img width="478" alt="Screenshot 2024-07-08 at 8 17 58 PM" src="https://github.com/patrykandpatrick/vico/assets/2466073/8b57b435-6583-4e15-a8e9-dd07f48e27bd">

### Expected behavior

Expected to see the labels correctly as `1, 5, 10, 15, 20, 25, 31`

Notice below image! When using a different formatter, it shows a lot more labels. So clearly there is no issue of not having enough space, but when `labelsWithEmptyString` is provided to the formatter than we lose labels like `10` and chart looks broken

<img width="479" alt="Screenshot 2024-07-08 at 8 18 27 PM" src="https://github.com/patrykandpatrick/vico/assets/2466073/8a0a6976-5469-44fb-82e9-e8e2eef9c374">

### Vico version(s)

2.0.0-alpha.22

### Android version(s)

Any

**Comment by findjigar** [comment]
It's related to #776 but it has been marked as `non-bug`, so I created this issue as it seems very much a bug to me.

**Comment by Gowsky** [comment]
Hi @findjigar, you shouldn't control which _x_ values are labeled by returning empty strings from the formatter. There is a difference between an empty label and no label. This control is the responsibility of `AxisItemPlacer.Horizontal`. Please [see here](https://github.com/patrykandpatrick/vico/issues/731#issuecomment-2132788557) for an example of how to use it for labels that are not evenly spaced. The _x_ axis will then behave as you expect.

>So clearly there is no issue of not having enough space, but when labelsWithEmptyString is provided to the formatter than we lose labels like 10 and chart looks broken

Actually, as you can see in both cases the spacing is increased to 2 for the labels to fit. The labels with empty strings probably could fit with a spacing of 1. But some assumptions are made during calculation and they only work when the API is used the proper way.

>It's related to https://github.com/patrykandpatrick/vico/issues/776 but it has been marked as non-bug, so I created this issue as it seems very much a bug to me.

That issue relates to something else, and as @patrickmichalik mentioned, the suboptimal behavior described there is fixed in Vico 2.

**Comment by findjigar** [comment]
ok thanks. I'll check that out

**Comment by diegoup2** [comment]
@Gowsky Is there a way to actually make it multi line? 

Im using this: 
`HorizontalAxis.ItemPlacer.default(spacing = 1, shiftExtremeTicks = false, addExtremeLabelPadding = false)`
![Screenshot 2024-07-26 at 11 44 56 AM](https://github.com/user-attachments/assets/4ca87146-704b-4548-ba45-48f74b476e3d)

**Comment by Gowsky** [comment]
@diegoup2, yes. Please see [here](https://github.com/patrykandpatrick/vico/discussions/628#discussioncomment-9960199).

**Comment by diegoup2** [comment]
@Gowsky Thanks for the answer, unfortunately doesnt work with line count.

``` 
rememberBottomAxis(
                valueFormatter = chartValueFormatter,
                titleComponent = rememberTextComponent(
                    typeface = AppTheme.GraphAxisLabel.toGraphicsTypeFace(),
                    lineCount = 2
                ),
                itemPlacer =
                remember {
                    HorizontalAxis.ItemPlacer.default(
                        spacing = 1,
                        shiftExtremeTicks = false,
                        addExtremeLabelPadding = false
                    )
                }
            )
            ```
