### ISSUE TITLE
Examples still use deprecated CartesianChartModelProducer.build() function

### ISSUE THREAD

**Issue by ericswpark** [patrykandpatrick/vico#792]
### Area

See the documentation here: https://patrykandpatrick.com/vico/wiki/cartesian-charts/layers/line-layer/#basic

### Error

It should be updated to use the new constructor style:

```kotlin
val modelProducer = remember { CartesianChartModelProducer() }
```

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. This will be corrected.

**Comment by patrickmichalik** [comment]
The fix is live. Cheers!
