### ISSUE TITLE
label color not change in 2.0.0-alpha.24

### ISSUE THREAD

**Issue by keyvanNorouzi** [patrykandpatrick/vico#806]
### How to reproduce

Label color not change in both startAxis and bottom axis

     label =
                            rememberTextComponent(
                                typeface = Typeface.MONOSPACE,
                                color = MaterialTheme.colorScheme.primary,
                                margins = Dimensions.of(horizontal = 4.dp, vertical = 2.dp),
                            ),

### Observed behavior

Label color not change in both startAxis and bottom axis

### Expected behavior

label color should change color of labels

### Vico version(s)

2.0.0-alpha.23

### Android version(s)

14

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into it.

**Comment by patrickmichalik** [comment]
We have a hotfix ready, but for the past few hours, we’ve been facing a Maven Central issue that makes releasing updates impossible. We’re waiting for the problem to be resolved. Thanks for your patience.

**Comment by patrickmichalik** [comment]
The update, [Vico 2.0.0 Alpha 25](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.25), is now rolling out. Cheers!
