### ISSUE TITLE
Line color doesn't update when negative/positive values change

### ISSUE THREAD

**Issue by mak1nt0sh** [patrykandpatrick/vico#809]
### How to reproduce

```
    CartesianChartHost(
        chart = rememberCartesianChart(
            rememberLineCartesianLayer(
                lineProvider = LineCartesianLayer.LineProvider.series(
                    rememberLine(
                        shader = TopBottomShader(
                            topShader = DynamicShader.color(MaterialTheme.colorScheme.primary),
                            bottomShader = DynamicShader.color(MaterialTheme.customColors.negative)
                        )
                    )
                )
            ),
        modelProducer = graphModelProducer,
        scrollState = rememberVicoScrollState(scrollEnabled = false)
    )
```

### Observed behavior

Initial colors are good. However when the data refreshes the line seems to remember previous splitY value and doesn't update. The background color is updating though.

<img width="492" alt="Screenshot 2024-07-23 at 11 40 38" src="https://github.com/user-attachments/assets/b769ecd0-e407-4827-9bec-1dd7301ec40e">
<img width="483" alt="Screenshot 2024-07-23 at 11 40 55" src="https://github.com/user-attachments/assets/736cc023-d4cf-44d4-9636-f7d3ef2366ed">

### Expected behavior

All was working on alpha.22. The line color respected splitY = 0

### Vico version(s)

2.0.0-alpha.24

### Android version(s)

Any

**Comment by patrickmichalik** [comment]
Hello, and thanks for the report! We’re working on changes that will fix both this and the problem reported in issue #784.

The unexpected `DefaultCartesianMarker` label color is a direct result of the bug at hand. Regarding no `Component` being drawn on the line, this is expected—the default `indicator` value is (and always has been) `null`. You can add an indicator by passing a lambda that returns a `Component`. Here’s a simple example:

```kt
rememberDefaultCartesianMarker(
  label = rememberTextComponent(),
  indicator = remember { { shapeComponent(it, Shape.Pill) } },
)
```

We plan on introducing non-null defaults for `indicator` and `guideline`.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 26](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.26) resolves this. Cheers!

**Comment by mak1nt0sh** [comment]
Just checked the alpha26, it's better but there are still same issues present. Now for zero values the line is split and for mixed negative/positive the marker color returns negative color for positive values in some cases.

```
chart = rememberCartesianChart(
            rememberLineCartesianLayer(
                lineProvider = LineCartesianLayer.LineProvider.series(
                    rememberLine(
                        fill = LineCartesianLayer.LineFill.double(
                            topFill = fill(MaterialTheme.colorScheme.primary),
                            bottomFill = fill(MaterialTheme.customColors.negative)
                        )
                    )
            )
```

![oie_bbihTnxyTT3I](https://github.com/user-attachments/assets/7511ea35-d4c6-47a2-ae96-cb179c96e62a)
![oie_ve3UksPsF92S](https://github.com/user-attachments/assets/93df8c26-d134-426e-9e88-88e129fb7498)

**Comment by patrickmichalik** [comment]
Thanks for letting us know, @mak1nt0sh! Since this is more closely related to issue #784, I’ve reopened that. Please see [here](https://github.com/patrykandpatrick/vico/issues/784#issuecomment-2258985313).
