### ISSUE TITLE
Bug with the label text color 

### ISSUE THREAD

**Issue by ihajat** [patrykandpatrick/vico#834]
### How to reproduce

the label text color seems to be overwritten with line color

### Observed behavior

same as line color

### Expected behavior

should be different color, cause I changed it to a different color

### Vico version(s)

2.0.0-alpha.27

### Android version(s)

14

**Comment by ihajat** [comment]
ver 1.15.0

**Comment by Gowsky** [comment]
Hi @ihajat, the `DefaultLabelFormatter` applies color to labels using `SpannableString`. You can turn it off via `colorCode` constructor parameter. See the [API reference](https://patrykandpatrick.com/vico/api/1.15.0/core/com.patrykandpatrick.vico.core.marker/-default-marker-label-formatter/).
Please share your code if you need help with this.
