### ISSUE TITLE
DefaultCartesianMarker ignores the text component label color

### ISSUE THREAD

**Issue by Tyler-Lopez** [patrykandpatrick/vico#853]
### How to reproduce

Attempt to set the default cartesian marker's label text color to a value that does not match the color of the line.

### Observed behavior

The text color always matches the line color of the corresponding line.

### Expected behavior

It should be what I set it to.

### Vico version(s)

2.0.0-alpha.27

### Android version(s)

33

**Comment by Tyler-Lopez** [comment]
This is solved through 
```kotlin
    return rememberDefaultCartesianMarker(
        label = label,
        valueFormatter = DefaultCartesianMarkerValueFormatter(
            colorCode = false,
        )
```

**Comment by patrickmichalik** [comment]
Thanks for sharing the solution!
