### ISSUE TITLE
Cant get Data form chartValues when Market Clicked -  v2.0.0-alpha.28

### ISSUE THREAD

**Issue by keyvanNorouzi** [patrykandpatrick/vico#854]
### How to reproduce

    val labelFormatter: CartesianMarkerValueFormatter =
        CartesianMarkerValueFormatter { context, targets -> 
// want x from chart value formater to show in market popup
context.chartValues.model.extraStore.getOrNull(ExtraStore.Key<List<String>>())
}

it gets null

### Observed behavior

get null from market value formater

### Expected behavior

get X value from chart formater

### Vico version(s)

2.0.0-alpha.27

### Android version(s)

14

### Additional information

if I use 
Gson().toJson(context.chartValues.model.extraStore)
I cant see data in Json format, but I cant get data from cahrtValues

**Comment by Gowsky** [comment]
Hi @keyvanNorouzi. You can't create an `ExtraStore.Key` instance at the `ExtraStore.getOrNull` function call, as it will never work. Keys are compared by instance. You can learn more about the keys in [the wiki](https://patrykandpatrick.com/vico/wiki/cartesian-charts/data#asynchrony-and-extras).

**Comment by Gowsky** [comment]
Also, you don't need `ExtraStore` to obtain the information about marked entries. Information on the marked entries is in `targets`.
