### ISSUE TITLE
OOM caused by `HorizontalAxis.ItemPlacer.aligned()` when an axis has no `label`

### ISSUE THREAD

**Issue by Gowsky** [patrykandpatrick/vico#890]
### How to reproduce

Reproduced in our internal testing

### Observed behavior

OOM

### Expected behavior

No OOM.

### Vico version(s)

2.0.0-beta.1

### Android version(s)

Any

**Comment by patrickmichalik** [comment]
Until a fix is released, you can resolve this by setting `addExtremeLabelPadding` to `false` in `HorizontalAxis.ItemPlacer.aligned`. (@papajul, this may be of interest to you.)

**Comment by patrickmichalik** [comment]
Until a fix is released, you can resolve this by setting `addExtremeLabelPadding` to `false` in `HorizontalAxis.ItemPlacer.aligned`. (@papjul, this may be of interest to you.)

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Beta 2](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-beta.2) fixes this.
