### ISSUE TITLE
2.0.0-beta.1 Introduces Failure to Recompose Line

### ISSUE THREAD

**Issue by Tyler-Lopez** [patrykandpatrick/vico#900]
### How to reproduce

Hi there!

I believe that `2.0.0-beta.1` introduces a new bug. I have included reproducible examples and videos. 

When a property of a `LineCartesianLayer` is changed, the style _should_ recompose.

In `2.0.0-alpha.28`, if I have a state parameter that is used for the thickness of the line, when it changes, I successfully see the line update.

This gist demonstrates a successful case in `2.0.0-alpha.28`.

https://gist.github.com/Tyler-Lopez/39f0768ce9dd2c0aec8c281aa702033b

If I take the same code and update my version to `2.0.0-beta1`, it no longer successfully updates. 

This gist demonstrates a failure case in `2.0.0-beta1`.

https://gist.github.com/Tyler-Lopez/7ca8630b7bb8e7bee26d73dfb964cbb9

I was drawn to pursue this as a possible reason for the problem as part of the change between the versions is how `rememberLine` is invoked. I have tried not using that function in the beta and was also unsuccessful.

### Observed behavior

https://github.com/user-attachments/assets/aeef03e2-86d5-4496-89a1-72fd1a166f3a

### Expected behavior

https://github.com/user-attachments/assets/1c114584-cf5d-44eb-a060-b9869fc7c4d6

### Vico version(s)

2.0.0-beta.1

### Android version(s)

33

### Additional information

I think it would be great if one of the "example charts" on the showcase app featured style state-mutation like this. Maybe this is something I could contribute towards? 

In my app, I am working on developing such a "showcase page" to make sure the chart always works as expected.

**Comment by Gowsky** [comment]
Hello, @Tyler-Lopez. This is caused by strong skipping mode being enabled by default in Kotlin 2.0.20. We are looking into it.
