### ISSUE TITLE
Last marker color is black when both axis are null and using `LineCartesianLayer.LineFill.double` or `padding`

### ISSUE THREAD

**Issue by mak1nt0sh** [patrykandpatrick/vico#902]
### How to reproduce

Create a MVP of line chart with `padding` and `LineCartesianLayer.LineFill.double`:

```
    CartesianChartHost(
        modifier = Modifier.height(150.dp).padding(8.dp),
        chart = rememberCartesianChart(
            rememberLineCartesianLayer(
                lineProvider = LineCartesianLayer.LineProvider.series(
                    LineCartesianLayer.rememberLine(
                        fill = LineCartesianLayer.LineFill.double(
                            topFill = fill(Color.Green),
                            bottomFill = fill(Color.Red)
                        )
                    )
                )
            ),
            marker = rememberDefaultCartesianMarker(
                label = rememberTextComponent()
            )
        ),
        modelProducer = graphModelProducer
    )
```

### Observed behavior

Selecting last marker results in black color:

<img width="79" alt="Screenshot 2024-10-01 at 13 43 23" src="https://github.com/user-attachments/assets/a1e59c76-d38c-49a2-81e7-07248d999feb">

### Expected behavior

Without `padding` or using `LineCartesianLayer.LineFill.single` the color is correct:

<img width="102" alt="Screenshot 2024-10-01 at 13 46 17" src="https://github.com/user-attachments/assets/82afded4-871d-451b-a2d0-d112b869bd02">

### Vico version(s)

2.0.0-beta.1

### Android version(s)

Any

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into this.
