### ISSUE TITLE
Cubic Bezier curve is not smooth after addition of more points

### ISSUE THREAD

**Issue by dmytroreutov** [patrykandpatrick/vico#911]
### How to reproduce

Given, 2 styles with 100% curvature:
 
```
    <style name="ChartLineStyleDownload">
        <item name="color">@color/speedtest_chart_line_download_start</item>
        <item name="thickness">3dp</item>
        <item name="curvature">100%</item>
    </style>

    <style name="ChartLineStyleUpload">
        <item name="color">@color/speedtest_chart_line_upload_start</item>
        <item name="thickness">3dp</item>
        <item name="curvature">100%</item>
    </style>

    <style name="ChartLineLayerStyle">
        <item name="line1Style">@style/ChartLineStyleDownload</item>
        <item name="line2Style">@style/ChartLineStyleUpload</item>
    </style>
```
Added ~ 15 points (limited by `AxisValueOverrider#getMaxX` and by dataset throttling)

Data samples:

```
downloadSet=[
	0.0, 
	38.146683, 
	242.03212, 
	292.12222, 
	319.12756, 
	329.35614, 
	325.19464, 
	328.08115, 
	330.28174, 
	331.8508, 
	334.11844, 
	334.89322, 
	335.93442, 
	336.3754, 
	335.7281
]
```
and 

```
uploadSet=[
	0.0, 
	33.290024, 
	132.90515, 
	191.69855, 
	221.42986, 
	252.92613, 
	272.6088, 
	286.07413, 
	283.66812, 
	292.57675, 
	309.16382, 
	305.22266, 
	309.87167, 
	313.76608, 
	311.44153
]
```

### Observed behavior

At some point (maybe after a third of dataset added or a little bit earlier), chart lines begin to look choppy and not smooth as can be seen on screenshots. 

![photo_2024-10-07 13 22 19](https://github.com/user-attachments/assets/a94e60c2-b74b-4da3-954c-7f3272a317e8)
![photo_2024-10-07 13 22 23](https://github.com/user-attachments/assets/29993709-858e-47cb-b646-9f5682ac7693)
![photo_2024-10-07 13 22 25](https://github.com/user-attachments/assets/570d25d5-800d-4a26-9ef0-8d1d8d9927cb)
![photo_2024-10-07 13 22 27](https://github.com/user-attachments/assets/1e846fb3-7297-47c0-bac5-6077ee518eeb)

### Expected behavior

As a user I expect a smooth line from first point to last. Maybe you can suggest how can i customise `CubicPointConnector`

### Vico version(s)

2.0.0-beta.1

### Android version(s)

14

### Additional information

Views version

**Comment by Gowsky** [comment]
Hello, @dmytroreutov. These are mathematically accurate cubic curves through the given points. It's working correctly, and the expected behavior is vague and purely subjective, so I'm closing the bug report.

> As a user I expect a smooth line from first point to last.

Please be more specific. What is "a smooth line from first point to last" exactly? Past a certain level of smoothness, the line would no longer go through the points.

>Maybe you can suggest how can i customise `CubicPointConnector`

`CubicPointConnector` cannot be customized, but you can create your own `PointConnector` to connect the points however you like.

**Comment by dmytroreutov** [comment]
Sorry for misleading you.
For example, on given screenshot, everything before pink line (kinda) looks "smooth".
Anything added after it made path look like more angled. 

![photo_2024-10-07 19 45 54](https://github.com/user-attachments/assets/af08788e-5c64-4e04-b2c4-37f4135b198b)

**Comment by dmytroreutov** [comment]
This is hard to see, but maybe video can show better.

https://github.com/user-attachments/assets/b711e5fa-4617-47b7-a591-070476092a97

**Comment by dmytroreutov** [comment]
It appears more noticable with larger dataset (35 vs 15)

https://github.com/user-attachments/assets/f3d90566-de7d-42af-afc7-213ddae55c46

**Comment by Gowsky** [comment]
`CubicPointConnector` adjusts the curvature based on the difference in _y_ value. This prevents the line from being too wavy. Perhaps the calculation should be adjusted to preserve a bit more curvature. We'll look into it.

In the meantime, as I mentioned above, you can create your own `PointConnector` to achieve any result you'd like. You can use [the `CubicPointConnector` definition](https://github.com/patrykandpatrick/vico/blob/master/vico/core/src/main/java/com/patrykandpatrick/vico/core/cartesian/layer/CubicPointConnector.kt) as a starting point. Try increasing `Y_MULTIPLIER` or removing [this part](https://github.com/patrykandpatrick/vico/blob/master/vico/core/src/main/java/com/patrykandpatrick/vico/core/cartesian/layer/CubicPointConnector.kt#L41) completely. The custom `PointConnector` can be applied via `LineCartesianLayer.Line.pointConnector`.
