### ISSUE TITLE
Crash in LineCartesianLayer: drawInternal  STACK_TRACE=java.lang.IllegalArgumentException: Cannot round NaN value.

### ISSUE THREAD

**Issue by zell-mbc** [patrykandpatrick/vico#920]
### How to reproduce

Right now I can only reproduce this error inside my app, and also only with a very specific test dataset which one of my users sent me. After some investigation it turns out that my app crashes if all y-axis values are identical. Like here
![image](https://github.com/user-attachments/assets/ca3dbc61-c8d6-4f00-a475-964ff3baf88b)

If I change just one entry to 201, things are good. All 4 records to 300 leads to a crash

### Observed behavior

According to my crash log the app crashes in line 387 of  LineCartesianLayer.kt, and when debugging I see limitedCanvasY is indeed "NaN". So I walked up backwards to see where the "NaN" comes from and landed in line 333:
![image](https://github.com/user-attachments/assets/8da26b89-ac4c-4ea6-b9aa-a05c10ca0fe7)

Here's a screenshot right before I walk into `forEachPoint…`, 4 items, all with different x values and valid but identical y values.
![image](https://github.com/user-attachments/assets/25457706-5fd7-44da-9980-84d3253c78e7)

And finally here's where things get stuck:
![image](https://github.com/user-attachments/assets/4e9a5c2a-5866-4a92-b97d-19711f02cc67)
I don't exactly understand what's going on here but I'd say here's a division through 0 which you try to convert to a float. And that's probably where the "NaN" stems from? Both `entry.y` and `yRange.minY` are 200, which is another 0 in the formula.

### Expected behavior

Catch error in cases where all y values are identical

### Vico version(s)

2.0.0-beta.1

### Android version(s)

Any

**Comment by Gowsky** [comment]
Hello, @zell-mbc. It looks like you've applied a `CartesianLayerRangeProvider` that uses the data's _y_ range unconditionally. In this case, that means that you're setting identical minimum and maximum _y_ values, which is incorrect. It would imply that the chart is infinitely zoomed in vertically. You should update your `CartesianLayerRangeProvider` to return a valid _y_ range when the data's _y_ range is zero-length.

**Comment by zell-mbc** [comment]
I did indeed, mea culpa :-/
