### ISSUE TITLE
Updating RangeProvider does not update without new data

### ISSUE THREAD

**Issue by Tyler-Lopez** [patrykandpatrick/vico#932]
### How to reproduce

Hi there!

### Summary

I am working on taking Vico and developing a demonstration of many chart state mutations. For example, dynamically adding and removing data series or styling them dynamically.

Since the recomposition issue of `2.0.0-beta.1` was fixed, I can successfully update the style of a layer dynamically and see that updated instantly.

However, I noticed when dynamically mutating a `rangeProvider` that it does not update until I update the data series values. It also does not update when I do see successful updates of a layer's style, like by changing the line thickness. This also was the case with the previous `AxisValueOverrider`.

Could we consider this a bug? I would think we should see the new state reflected in the chart here. It being something I would expect to happen is why I chose to classify this as an issue rather than a feature request. Happy to provide a more concrete example as necessary.

### Video Demonstration

The video opens by demonstrating that I can change the style of the chart and instantly see those updates reflected.

I then toggle "Use Custom Y-Axis Range" and note that nothing happens to the chart as I change the values.

I show that I can still change the style of the chart and that update happens. It is only when I click "Randomize Y Values" do I see an update in the range provider.

https://github.com/user-attachments/assets/ddb4ea4a-748b-4af1-befe-f9372c97672f

### Observed behavior

Updating `rangeProvider` dynamically does not take effect until the data series updates - like by actually updating the values, for example.

### Expected behavior

Updating `rangeProvider` should instantly be reflected in the chart.

### Vico version(s)

2.0.0-beta.1

### Android version(s)

33

### Additional information

Actual version is `2.0.0-beta.2` which was not an option.

**Comment by Gowsky** [comment]
Hello, @Tyler-Lopez. This is working as expected. It is possible to change the ranges without updating the series, but you should do so using extras. This is described [in the wiki](https://patrykandpatrick.com/vico/wiki/cartesian-charts/layers/#cartesianlayerrangeprovider) and discussed more generally [here](https://github.com/patrykandpatrick/vico/discussions/674#discussioncomment-9444387).

**Comment by Tyler-Lopez** [comment]
Thanks so much for pointing me in that direction @Gowsky!

I looked into the extras, and very quickly had it working great. However, I think I may have found a related bug to raise, unless I am missing something else key.

When I rapidly create many transactions, like when I initiate the running of a transaction that mutates the extras here, I seem to lock up the ability to make subsequent transactions. That includes unrelated things like randomizing my y-values.

Do you have any thoughts here? I've attached a video demonstrating no issue when I discreetly click the range slider, but a fairly immediate freeze upon dragging it.

I have not yet attempted to see if rapidly changing a transaction from other sources, like a `lineSeries` has the same effect.

https://github.com/user-attachments/assets/94d559f5-3531-41a9-bdba-5f69a2a717b1

**Comment by Gowsky** [comment]
Please share an MRE, so we can look into this.

**Comment by Tyler-Lopez** [comment]
@Gowsky Totally, happy to!

Here is a gist containing an MRE https://gist.github.com/Tyler-Lopez/2d8f5a1074dac056a954b0407c14630b 

Unlike the previous example, I did notice some additional weirdness where it seemed like _sometimes_ clicking to increment the end resulted in nothing happening. That wasn't a lock-out situation though.

In the video, I demonstrate how it works correctly when clicked discretely, except for that one weird exception where sometimes clicking towards the end didn't recompose, and I demonstrate that once I start dragging it locks up quickly.

This is on a physical Samsung S23 device.


https://github.com/user-attachments/assets/0a2d627e-b24e-4d73-838f-90eb6070b6e0

**Comment by Gowsky** [comment]
Thanks, @Tyler-Lopez! The code looks correct. Can you open a dedicated bug report and include a link to this MRE?
