### ISSUE TITLE
Very rapid transactions cause transaction lock-out

### ISSUE THREAD

**Issue by Tyler-Lopez** [patrykandpatrick/vico#933]
### How to reproduce

[I was looking into how to have changes to the range provider instantly ](https://github.com/patrykandpatrick/vico/issues/932)update the chart and was pointed to use `ExtraStore` and running transactions to update the `extras -> extraStore` as the range changes. That solution worked great, however, I found that when I rapidly updated the transactions I would get into a state where I was completely locked out from all transactions: including mutations to the values. Specifically, the UI element facilitating rapid update was a range slider.

I created this [MRE](https://gist.github.com/Tyler-Lopez/2d8f5a1074dac056a954b0407c14630b) which demonstrates this. I've updated this since the original issue slightly

The MRE contains two UI control sliders:

- The first shuffles the x-values when changed.
- The second updates the x-axis range when changed.

In both cases (I originally observed the issue with just the x-axis range), updates are reflected when you click. If you drag, the UI very quickly locks up, and any subsequent clicks or drags will fail to do anything.

 

https://github.com/user-attachments/assets/c9da50ce-c9c3-4d02-aa98-5dd0addcef4c

### Observed behavior

Rapidly changing a key to the `LaunchedEffect` which results in `modelProducer.runTransaction` updates breaks all subsequent updates.

### Expected behavior

Rapidly changing a key to the `LaunchedEffect` which results in `modelProducer.runTransaction` updates should not break subsequent updates.

### Vico version(s)

2.0.0-beta.2

### Android version(s)

33

### Additional information

Physical Samsung Galaxy S23 device.

**Comment by Tyler-Lopez** [comment]
I have also found another case that triggers this, where I run a transaction on `zoomState.value` change to add that value to the `ExtraStore`. That triggers too rapidly on zooming in and so this state occurs.

**Comment by Tyler-Lopez** [comment]
I noticed that things also similarly go awry for likely the same reason when `zoomState.value` is added as a key to the `LaunchedEffect` which runs a transaction. The idea for doing that would be if you wanted to put the zoom state value into the `ExtraStore`. You would do that if you wanted something to be the same size across zoom levels, like the space between bars in a bar chart.

**Comment by Gowsky** [comment]
Hello, @Tyler-Lopez. Thank you for the report. We'll look into it.

> if you wanted to put the zoom state value into the `ExtraStore`. You would do that if you wanted something to be the same size across zoom levels, like the space between bars in a bar chart.

Extras aren't needed for `VicoZoomState.value` — you should use it directly. More importantly, the particular solution you've described is a workaround that should be avoided. The definition of a zoom factor is that the content is scaled **proportionally**. If you interfere with this by changing the intrinsic size based on the zoom factor, then unexpected behavior may occur. It's essentially fighting against the zoom system. Please open a feature request for zoom-independent column spacing, so this is implemented at the library level in a correct manner.

**Comment by patrickmichalik** [comment]
Hello! Please also note that for persistent extras—that is, extras added on every `Transaction`—the `ExtraStore.get` operator function is preferable to `ExtraStore.getOrNull`. Persistent extras are guaranteed to be present in the `ExtraStore`. `ExtraStore.getOrNull` is intended for extras that are added conditionally.

Thus, the `CartesianLayerRangeProvider` definition from the example provided can be simplified as follows:

```kt
object : CartesianLayerRangeProvider {
    override fun getMinX(minX: Double, maxX: Double, extraStore: ExtraStore) =
        extraStore[xAxisRangeKey].start.toDouble()

    override fun getMaxX(minX: Double, maxX: Double, extraStore: ExtraStore) =
        extraStore[xAxisRangeKey].endInclusive.toDouble()
}
```

**Comment by Gowsky** [comment]
[Vico `2.0.0-beta.5`](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-beta.5) fixes this.

Also, please note that the `ExtraStore.get` observation from [this comment](https://github.com/patrykandpatrick/vico/pull/934#issuecomment-2494693437) also applies to the MRE shared here: `extraStore[...]` should be used instead of `extraStore.getOrNull(...)`.
