### ISSUE TITLE
Expose custom marker code

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [patrykandpatrick/vico#980]
### Area

The custom marker design shown in the pictures through the documentation should be exposed, at least in the documentation.
![marker](https://github.com/user-attachments/assets/1690db05-ecf3-4534-8eee-1ca66833550f)

### Error

I cannot find the code that produces this design anywhere and I am so far unable to replicate it myself.
If any of you here have the snippet that produces such code, please share it.

### Additional information

I'm using Compose with the M3 Theme.

**Comment by Gowsky** [comment]
Hello, @TheOneTheOnlyJJ. It's in the sample app.

Please also note that even if the code weren't exposed, this wouldn't be a documentation error but rather a suggestion, so a discussion in "Ideas" would be more appropriate.
