### ISSUE TITLE
Cannot create DynamicShader with gradient at specific positions

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [patrykandpatrick/vico#981]
### How to reproduce

I have a line chart with a computed range that ceils the max and floors the min of some time series data that tracks temperature.
```kotlin
val timeSeriesTemps = /* code that gets the time series data */
val minYRange = remember { floor(minTemp).toDouble() }
val maxYRange = remember { ceil(maxTemp).toDouble() }
val rangeProvider = remember { CartesianLayerRangeProvider.fixed(
    minX = 0.toDouble(),
    maxX = (timeSeriesTemps.size - 1).toDouble(),
    minY = minYRange,
    maxY = maxYRange
) }

val modelProducer = remember { CartesianChartModelProducer() }

LaunchedEffect(Unit) {
    modelProducer.runTransaction {
        lineSeries {
            series(y = timeSeriesTemps)
        }
    }
}

CartesianChartHost(
        chart = rememberCartesianChart(
            rememberLineCartesianLayer(
                lineProvider = LineCartesianLayer.LineProvider.series(
                    LineCartesianLayer.rememberLine(
                        fill = LineCartesianLayer.LineFill.single(
                            getChartColorFill(
                                minY = minYRange,
                                maxY = maxYRange
                            )
                        ),
                        areaFill = LineCartesianLayer.AreaFill.single(
                            getChartColorFill(
                                minY = minYRange,
                                maxY = maxYRange,
                                alpha = 0.2f
                            )
                        )
                    )
                ),
                rangeProvider = rangeProvider
            ),
            startAxis = VerticalAxis.rememberStart(),
            bottomAxis = HorizontalAxis.rememberBottom()
        ),
        modelProducer = modelProducer,
        scrollState = rememberVicoScrollState(),
        zoomState = rememberVicoZoomState(),
        modifier = Modifier.fillMaxWidth().height(350.dp)
    )
```

I want to have a gradient going from the "coldColor" (a blue) to the "hotColor" (a red). This gradient is applied between 30 and 70 degrees. Anything under 30 degrees uses the pure coldColor and anything over 70 uses the pure hotColor. Many items on my UI conform to this color mapping. I want this chart to do the same, mapping the temperatures to a gradient depending on the values (y axis).

For simple colors, I've got this function that computes the linear interpolation mapped between 30 and 70 degrees:
```kotlin
val coldColor = Color(0xFF257ca3)
val hotColor = Color(0xFFDC143C)

const val COLD_COLOR_GRADIENT_THRESHOLD = 30f
const val HOT_COLOR_GRADIENT_THRESHOLD = 70f

private fun Double.mapToRange(min: Float, max: Float): Float {
    return (this.toFloat() - min) / (max - min)
}
fun getTempColor(temp: Double): Color {
    return lerp(coldColor, hotColor, temp.mapToRange(COLD_COLOR_GRADIENT_THRESHOLD, HOT_COLOR_GRADIENT_THRESHOLD))
}
```

While for the chart, I wrote a function that applies a `DynamicShader` fill, using the `verticalGradient` constructor that accepts a `positions` `FloatArray`. I have commented out the dead code from the example, for simple illustration purposes:
```kotlin
@Composable
fun getChartColorFill(minY: Double, maxY: Double, alpha: Float = 1f): Fill {
    var gradientHotColor: Color = getTempColor(maxY)
    var gradientColdColor: Color = getTempColor(minY)
    if (alpha != 1f)  {
        gradientHotColor = gradientHotColor.copy(alpha = alpha)
        gradientColdColor = gradientColdColor.copy(alpha = alpha)
    }
    val colorSteps = mutableMapOf<Int, Float>()
    return when {
        // Full cold color when max is below threshold
        maxY <= COLD_COLOR_GRADIENT_THRESHOLD -> fill(gradientColdColor)
        // Full hot color when min is above threshold
        minY >= HOT_COLOR_GRADIENT_THRESHOLD -> fill(gradientHotColor)
        else -> {
            // Get gradient positions
            // val gradientStartPosition = ((COLD_COLOR_GRADIENT_THRESHOLD - minY) / (maxY - minY)).coerceIn(0.0, 1.0).toFloat()
            // val gradientEndPosition = ((HOT_COLOR_GRADIENT_THRESHOLD - minY) / (maxY - minY)).coerceIn(0.0, 1.0).toFloat()
            // Add positions as required
            colorSteps[gradientHotColor.toArgb()] = 0f
            colorSteps[gradientHotColor.toArgb()] = 0.15f
            colorSteps[gradientColdColor.toArgb()] = 0.25f
            colorSteps[gradientColdColor.toArgb()] = 1f
            // Create fill
            return fill(DynamicShader.verticalGradient(
                colors = colorSteps.keys.toIntArray(),
                positions = colorSteps.values.toFloatArray()
            ))
        }
    }
}
```
You can freely play around with the `colorSteps` values (the positions) that get passed to the `verticalGradient` constructor.

### Observed behavior

Changing the `colorStep` values mentioned above does not properly change the gradient drawn as the line's `areaFill`.
For example, having values `0f, 0.15f, 0.25f, 1f` is not that much different form having values `0f, 0.15f, 0.85f, 1f`, even though it should.

### Expected behavior

Changing the `colorStep` values changes the gradient.

### Vico version(s)

2.0.0-beta.4

### Android version(s)

compileSdk = 35; targetSdk = 34

**Comment by Gowsky** [comment]
Hello, @TheOneTheOnlyJJ. `getChartColorFill` is incorrect. From your code:

```kt
colorSteps[gradientHotColor.toArgb()] = 0f
colorSteps[gradientHotColor.toArgb()] = 0.15f
colorSteps[gradientColdColor.toArgb()] = 0.25f
colorSteps[gradientColdColor.toArgb()] = 1f
```

Since `colorSteps` is a map, you're not adding two stops at 0 and 0.15 for `gradientHotColor` but rather adding one stop at 0 and then overriding it with 0.15. It's similar for `gradientHotColor`. You should use a different data structure.

Also, please note that many parts of your code disregard the need for [synchronization](https://www.patrykandpatrick.com/vico/guide/latest/core/cartesian-charts/cartesian-chart-model-producer#224-asynchrony-and-extras) and are thus incorrect. This may lead to unexpected behavior, so it should be corrected. Please look into extras and using them with `CartesianLayerRangeProvider` `LineCartesianLayer.LineProvider`, etc.

Finally, in the future, please provide **complete** examples that reproduce the issue without requiring guesswork from the maintainers.

**Comment by TheOneTheOnlyJJ** [comment]
Thank you for pointing it out to me. I was getting exhausted at that point and completely missed the mistake.
I've just managed to make it work properly. For anyone interested, here's the code:
```kotlin
@Composable
fun getChartColorFill(minY: Double, maxY: Double, alpha: Float = 1f): Fill {
    var gradientHotColor: Color = getTempColor(maxY)
    var gradientColdColor: Color = getTempColor(minY)
    if (alpha != 1f)  {
        gradientHotColor = gradientHotColor.copy(alpha = alpha)
        gradientColdColor = gradientColdColor.copy(alpha = alpha)
    }
    val colorSteps = mutableListOf<Pair<Color, Float>>()
    return when {
        // Full cold color when max is below threshold
        maxY <= COLD_COLOR_GRADIENT_THRESHOLD -> fill(gradientColdColor)
        // Full hot color when min is above threshold
        minY >= HOT_COLOR_GRADIENT_THRESHOLD -> fill(gradientHotColor)
        else -> {
            // Get gradient positions
            val gradientColdSidePosition = ((COLD_COLOR_GRADIENT_THRESHOLD - minY) / (maxY - minY)).coerceIn(0.0, 1.0).toFloat()
            val gradientHotSidePosition = ((HOT_COLOR_GRADIENT_THRESHOLD - minY) / (maxY - minY)).coerceIn(0.0, 1.0).toFloat()
            // Add positions as required
            colorSteps.add(Pair(gradientHotColor, 0f))
            if (minY < HOT_COLOR_GRADIENT_THRESHOLD && maxY > HOT_COLOR_GRADIENT_THRESHOLD) {
                colorSteps.add(Pair(gradientHotColor, 1f - gradientHotSidePosition))
            }
            if (minY < COLD_COLOR_GRADIENT_THRESHOLD && maxY > COLD_COLOR_GRADIENT_THRESHOLD) {
                colorSteps.add(Pair(gradientColdColor, 1f - gradientColdSidePosition))
            }
            colorSteps.add(Pair(gradientColdColor, 1f))
            // Create fill
            return fill(DynamicShader.verticalGradient(
                colors = colorSteps.map { it.first.toArgb() }.toIntArray(),
                positions = colorSteps.map { it.second }.toFloatArray()
            ))
        }
    }
}
```

**Comment by Gowsky** [comment]
Please note that this is correct only if the _y_ range is static, meaning that it doesn't change over the chart's lifespan. This seems to be the case currently (based on the lack of `remember` keys for `minYRange` and `maxYRange`), but it's important to keep in mind that if the _y_ range were to be made dynamic, your logic would be affected by the lack of synchronization I mentioned.

For such cases, the correct solution would be to implement `LineFill` and `AreaFill`, retrieve the _y_ range via context, and generate a gradient based on this data. Similarly, for the `CartesianLayerRangeProvider`, you should then implement the interface and calculate the final _y_ range there, based on the `minY` and `maxY` arguments.
